package com.smoothradio.radio.feature.radiolist.util

import com.smoothradio.radio.R
import com.smoothradio.radio.core.domain.model.RadioStation

/**
 * Helper class for managing radio stations.
 *
 * This class provides utility functions related to radio station data,
 * such as creating a list of predefined radio stations and merging it
 * with locally stored station data (e.g., favorites, currently playing).
 */
class RadioStationsHelper {
    companion object {
        fun createRadioStations(linksList: List<String>): List<RadioStation> {
            val radioStationsList = mutableListOf<RadioStation>().apply {
                var index = 0 // Initialize the order index

                add(RadioStation(0, R.drawable.hopefm, "HOPE FM", "93.3", "NAIROBI", linksList[0], false, false, index++))
                add(RadioStation(1, R.drawable.soundcityradiologo, "SOUNDCITY RADIO", "88.5", "NAIROBI", linksList[1], false, false, index++))
                add(RadioStation(2, R.drawable.kissfm, "KISS FM", "100.3", "NAIROBI", linksList[2], false, false, index++))
                add(RadioStation(228, R.drawable.radio47logo, "RADIO 47", "103.0", "NAIROBI", linksList[228], false, false, index++))
                add(RadioStation(3, R.drawable.nrg0, "NRG RADIO", "97.1", "NAIROBI", linksList[3], false, false, index++))
                add(RadioStation(203, R.drawable.radiocitizenlogo, "RADIO CITIZEN", "106.7", "NAIROBI", linksList[203], false, false, index++))
                add(RadioStation(4, R.drawable.inooro, "INOORO FM", "98.9", "NAIROBI", linksList[4], false, false, index++))
//                 add(RadioStation(206, R.drawable.njatafmlogo,"NJATA FM","97.2","NAIROBI",linksFromTxt[206], false, false, index++))
                add(RadioStation(5, R.drawable.nrgchoiceradiologo, "CHOICE RADIO", "87.7", "NAIROBI", linksList[5], false, false, index++))
                add(RadioStation(6, R.drawable.hot96logo, "HOT 96", "96.0", "NAIROBI", linksList[6], false, false, index++))
                add(RadioStation(7, R.drawable.homeboys, "HOMEBOYS RADIO", "103.5", "NAIROBI", linksList[7], false, false, index++))
                add(RadioStation(8, R.drawable.classic105_logo, "CLASSIC 105", "105.2", "NAIROBI", linksList[8], false, false, index++))
                add(RadioStation(9, R.drawable.radiojambologo, "RADIO JAMBO", "97.5", "NAIROBI", linksList[9], false, false, index++))
                add(RadioStation(26, R.drawable.rogueradiologo, "ROGUE RADIO", "--.--", "NAIROBI", linksList[26], false, false, index++))
                add(RadioStation(30, R.drawable.tracefmlogo, "TRACE FM", "95.3", "NAIROBI", linksList[30], false, false, index++))
                add(RadioStation(10, R.drawable.corofmlogo, "CORO FM", "99.5", "NAIROBI", linksList[10], false, false, index++))
                add(RadioStation(11, R.drawable.kameme, "KAMEME FM", "101.1", "NAIROBI", linksList[11], false, false, index++))
                add(RadioStation(12, R.drawable.ghettoradiologo, "GHETTO RADIO", "89.5", "NAIROBI", linksList[12], false, false, index++))
                add(RadioStation(13, R.drawable.radiomaishalogo, "RADIO MAISHA", "102.7", "NAIROBI", linksList[13], false, false, index++))
                add(RadioStation(14, R.drawable.easyfmlogo, "EASY FM", "96.3", "NAIROBI", linksList[14], false, false, index++))
                add(RadioStation(15, R.drawable.ramogilogo, "RAMOGI FM", "107.1", "NAIROBI", linksList[15], false, false, index++))
                add(RadioStation(16, R.drawable.egesalogo, "EGESA FM", "98.6", "NAIROBI", linksList[16], false, false, index++))
                add(RadioStation(17, R.drawable.mulembelogo, "MULEMBE FM", "97.9", "NAIROBI", linksList[17], false, false, index++))
                add(RadioStation(18, R.drawable.musyilogo, "MUSYI FM", "102.2", "NAIROBI", linksList[18], false, false, index++))
                add(RadioStation(19, R.drawable.chamgeilogo, "CHAMGEI FM", "95.0", "NAIROBI", linksList[19], false, false, index++))
                add(RadioStation(25, R.drawable.kubambaradiologo, "KUBAMBA RADIO", "--.--", "NAIROBI", linksList[25], false, false, index++))
                add(RadioStation(27, R.drawable.truthfmlogo, "TRUTH FM", "90.7", "NAIROBI", linksList[27], false, false, index++))
                add(RadioStation(28, R.drawable.familyradiologo, "FAMILY RADIO", "103.9", "NAIROBI", linksList[28], false, false, index++))
                add(RadioStation(29, R.drawable.jesusislordradiologo, "JESUSISLORD RADIO", "105.3", "NAKURU", linksList[29], false, false, index++))
                add(RadioStation(31, R.drawable.xfmlogo, "SMOOTH FM", "105.5", "NAIROBI", linksList[31], false, false, index++))
                add(RadioStation(32, R.drawable.kigoocofmlogo, "KIGOOCO FM", "98.6", "NAIROBI", linksList[32], false, false, index++))
                add(RadioStation(38, R.drawable.kikuyudiasporaradiologo, "KENYA DIASPORA RADIO", "--.--", "ALABAMA", linksList[38], false, false, index++))
                add(RadioStation(33, R.drawable.mbciradiologo, "MBCI RADIO", "89.5", "NAKURU", linksList[33], false, false, index++))
//                add(RadioStation(224, R.drawable.gfnradiologo, "GFN FM", "90.1", "TURKANA", linksList[224], false, false, index++))
                add(RadioStation(44, R.drawable.nationfmlogo, "NATION FM", "96.3", "NAIROBI", linksList[44], false, false, index++))
                add(RadioStation(54, R.drawable.capitalfmlogo, "CAPITAL FM", "98.4", "NAIROBI", linksList[54], false, false, index++))
                add(RadioStation(231, R.drawable.kwitufmlogo, "KWITU FM", "90.1", "MACHAKOS", linksList[231], false, false, index++))
                add(RadioStation(41, R.drawable.gukenafmlogo, "GUKENA FM", "92.8", "NAIROBI", linksList[41], false, false, index++))
                add(RadioStation(20, R.drawable.muugalogo, "MUUGA FM", "94.2", "NAIROBI", linksList[20], false, false, index++))
                add(RadioStation(21, R.drawable.sulwelogo, "SULWE FM", "89.6", "NAIROBI", linksList[21], false, false, index++))
                add(RadioStation(22, R.drawable.wimwarologo, "WIMWARO FM", "93.0", "NAIROBI", linksList[22], false, false, index++))
                add(RadioStation(23, R.drawable.baharilogo, "BAHARI FM", "90.4", "MOMBASA", linksList[23], false, false, index++))
                add(RadioStation(24, R.drawable.vuukalogo, "VUUKA FM", "95.4", "NAIROBI", linksList[24], false, false, index++))
                add(RadioStation(92, R.drawable.lubaofmlogo, "LUBAO FM", "102.2", "KAKAMEGA", linksList[92], false, false, index++))
                add(RadioStation(34, R.drawable.iqrafmlogo, "IQRA FM", "95.0", "NAIROBI", linksList[34], false, false, index++))
                add(RadioStation(35, R.drawable.pwanifmlogo, "PWANI FM", "103.1", "MOMBASA", linksList[35], false, false, index++))
                add(RadioStation(36, R.drawable.sautiyapwanifmlogo, "SAUTIYAPWANI FM", "94.2", "MOMBASA", linksList[36], false, false, index++))
                add(RadioStation(37, R.drawable.kbcradiotaifalogo, "KBC RADIO TAIFA", "92.9", "NAIROBI", linksList[37], false, false, index++))
                add(RadioStation(39, R.drawable.taachfmlogo, "TAACH FM", "95.1", "ELDORET", linksList[39], false, false, index++))
                add(RadioStation(40, R.drawable.eastfmlogo, "EAST FM", "106.3", "NAIROBI", linksList[40], false, false, index++))
                add(RadioStation(42, R.drawable.kassfmlogo, "KASS FM", "89.1", "NAIROBI", linksList[42], false, false, index++))
                add(RadioStation(43, R.drawable.soundasialogo, "SOUNDASIA RADIO", "88.0", "NAIROBI", linksList[43], false, false, index++))
                add(RadioStation(45, R.drawable.wauminilogo, "RADIO WAUMINI", "88.3", "NAIROBI", linksList[45], false, false, index++))
                add(RadioStation(46, R.drawable.bibiliahusemalogo, "BIBILIA HUSEMA FM", "96.7", "NAIROBI", linksList[46], false, false, index++))
                add(RadioStation(47, R.drawable.heroradiologo, "HERO RADIO", "99.0", "NAKURU", linksList[47], false, false, index++))
                add(RadioStation(48, R.drawable.milelefmlogo, "MILELE FM", "104.8", "NAIROBI", linksList[48], false, false, index++))
                add(RadioStation(207, R.drawable.getembefmlogo, "GETEMBE FM", "102.7", "KISII", linksList[207], false, false, index++))
                add(RadioStation(208, R.drawable.inkafmlogo, "INKA FM", "93.7", "KISII", linksList[208], false, false, index++))
                add(RadioStation(49, R.drawable.radiokayalogo, "RADIO KAYA", "93.1", "NAIROBI", linksList[49], false, false, index++))
                add(RadioStation(50, R.drawable.spicefmlogo, "SPICE FM", "94.4", "NAIROBI", linksList[50], false, false, index++))
                add(RadioStation(51, R.drawable.barakafmlogo, "BARAKA FM", "95.5", "MOMBASA", linksList[51], false, false, index++))
                add(RadioStation(52, R.drawable.radioinjililogo, "RADIO INJILI", "103.7", "KERICHO", linksList[52], false, false, index++))
                add(RadioStation(53, R.drawable.athianilogo, "ATHIANI FM", "99.2", "NAIROBI", linksList[53], false, false, index++))
                add(RadioStation(55, R.drawable.beatlocklogo, "BEATLOCK RADIO", "--.--", "NAIROBI", linksList[55], false, false, index++))
                add(RadioStation(56, R.drawable.pearlxtralogo, "PEARL XTRA FM", "--.--", "NAIROBI", linksList[56], false, false, index++))
                add(RadioStation(57, R.drawable.theupperroomlogo, "THE UPPERROOM FM", "--.--", "NAIROBI", linksList[57], false, false, index++))
                add(RadioStation(58, R.drawable.lulufmlogo, "LULU FM", "91.0", "MOMBASA", linksList[58], false, false, index++))
                add(RadioStation(59, R.drawable.pearlradiologo, "PEARL RADIO", "96.9", "NAIROBI", linksList[59], false, false, index++))
                add(RadioStation(60, R.drawable.imaniradiologo, "IMANI RADIO", "88.8", "KITALE", linksList[60], false, false, index++))
                add(RadioStation(61, R.drawable.lionafriqradiologo, "LIONAFRIQ RADIO", "--.--", "NAIROBI", linksList[61], false, false, index++))
                add(RadioStation(211, R.drawable.nrg_hiphop_logo, "NRG HIPHOP", "--.--", "NAIROBI", linksList[211], false, false, index++))
                add(RadioStation(212, R.drawable.nrg_dancehall_logo, "NRG DANCEHALL", "--.--", "NAIROBI", linksList[212], false, false, index++))
                add(RadioStation(213, R.drawable.nrg_gospel_logo, "NRG GOSPEL", "--.--", "NAIROBI", linksList[213], false, false, index++))
                add(RadioStation(214, R.drawable.nrg_afrobeats_logo, "NRG AFROBEATS", "--.--", "NAIROBI", linksList[214], false, false, index++))
                add(RadioStation(215, R.drawable.nrg_mixology_logo, "NRG MIXOLOGY", "--.--", "NAIROBI", linksList[215], false, false, index++))
                add(RadioStation(216, R.drawable.nrg_rnb_logo, "NRG RNB", "--.--", "NAIROBI", linksList[216], false, false, index++))
                add(RadioStation(217, R.drawable.nrg_jazz_logo, "NRG JAZZ", "--.--", "NAIROBI", linksList[217], false, false, index++))
                add(RadioStation(204, R.drawable.longaradiologo, "LONGA RADIO", "--.--", "NAIROBI", linksList[204], false, false, index++))
                add(RadioStation(226, R.drawable.kayufmlogo, "KAYU FM", "91.0", "NAIROBI", linksList[226], false, false, index++))
                add(RadioStation(62, R.drawable.flamingoradiologo, "FLAMINGO FM", "93.7", "NAKURU", linksList[62], false, false, index++))
//                add(RadioStation(63, R.drawable.pilipilifmlogo, "PILIPILI FM", "99.5", "NAIROBI", linksList[63], false, false, index++))
                add(RadioStation(209, R.drawable.kerioradiologo, "KERIO RADIO", "87.6", "BARINGO", linksList[209], false, false, index++))
                add(RadioStation(210, R.drawable.tausifmlogo, "TAUSI FM", "--.--", "NAIROBI", linksList[210], false, false, index++))
                add(RadioStation(229, R.drawable.hillsidefmlogo, "HILLSIDE FM", "--.--", "NAIROBI", linksList[229], false, false, index++))
                add(RadioStation(230, R.drawable.pefaradoilogo, "PEFA RADIO", "--.--", "NAIROBI", linksList[230], false, false, index++))
                add(RadioStation(64, R.drawable.mayianfmlogo, "MAYIAN FM", "100.7", "NAROK", linksList[64], false, false, index++))
                add(RadioStation(65, R.drawable.merufmlogo, "MERU FM", "100.3", "MERU", linksList[65], false, false, index++))
                add(RadioStation(66, R.drawable.emoofmlogo, "EMOO FM", "104.2", "NAIROBI", linksList[66], false, false, index++))
                add(RadioStation(223, R.drawable.mutongoifmlogo, "MUTONGOI FM", "103.3", "KITUI", linksList[223], false, false, index++))
                add(RadioStation(218, R.drawable.mwagofmlogo, "MWANGO FM", "97.5", "NAIROBI", linksList[218], false, false, index++))
                add(RadioStation(219, R.drawable.nosimfmlogo, "NOSIM FM", "90.5", "NAIROBI", linksList[219], false, false, index++))
                add(RadioStation(220, R.drawable.osiepefmlogo, "OSIEPE FM", "96.8", "SIAYA", linksList[220], false, false, index++))
                add(RadioStation(67, R.drawable.radiosalaamlogo, "RADIO SALAAM", "90.7", "MOMBASA", linksList[67], false, false, index++))
                add(RadioStation(68, R.drawable.radiorahmalogo, "RADIO RAHMA", "91.5", "MOMBASA", linksList[68], false, false, index++))
//                add(RadioStation(69, R.drawable.asylumradiologo, "ASYLUM RADIO", "--.--", "NAIROBI", linksList[69], false, false, index++))
                add(RadioStation(70, R.drawable.kbcenglishservicelogo, "KBC ENGLISH SERVICE", "95.6", "NAIROBI", linksList[70], false, false, index++))
                add(RadioStation(71, R.drawable.mbaitufmlogo, "MBAITU FM", "92.5", "MACHAKOS", linksList[71], false, false, index++))
                add(RadioStation(72, R.drawable.radio_maria, "RADIO MARIA", "90.0", "NAIROBI", linksList[72], false, false, index++))
                add(RadioStation(73, R.drawable.upendoradiologo, "UPENDO RADIO", "89.4", "ELDORET", linksList[73], false, false, index++))
                add(RadioStation(74, R.drawable.hiphopginlogo, "HIPHOPGIN", "--.--", "NAIROBI", linksList[74], false, false, index++))
                add(RadioStation(75, R.drawable.hiphopdailylogo, "HIPHOP DAILY", "97.5", "NAIROBI", linksList[75], false, false, index++))
                add(RadioStation(79, R.drawable.rfmlogo, "R FM", "99.9", "LIMURU", linksList[79], false, false, index++))
                add(RadioStation(76, R.drawable.tulizafmlogo, "TULIZA FM", "94.2", "MERU", linksList[76], false, false, index++))
                add(RadioStation(77, R.drawable.kihootofmlogo, "KIHOOTO FM", "91.2", "NAIROBI", linksList[77], false, false, index++))
                add(RadioStation(78, R.drawable.kisiifmlogo, "KISII FM", "94.1", "NAIROBI", linksList[78], false, false, index++))
                add(RadioStation(80, R.drawable.seitofmlogo, "SEITO FM", "100.3", "NAIROBI", linksList[80], false, false, index++))
                add(RadioStation(81, R.drawable.sifafmlogo, "SIFA FM", "101.2", "MARSABIT", linksList[81], false, false, index++))
                add(RadioStation(82, R.drawable.countyfmlogo, "COUNTY FM", "90.3", "KITUI", linksList[82], false, false, index++))
                add(RadioStation(83, R.drawable.sidaifmlogo, "SIDAI FM", "103.5", "NAROK", linksList[83], false, false, index++))
                add(RadioStation(84, R.drawable.radioneemalogo, "RADIO NEEMA", "--.--", "NAIROBI", linksList[84], false, false, index++))
                add(RadioStation(85, R.drawable.radiosimbalogo, "RADIO SIMBA", "93.1", "BUNGOMA", linksList[85], false, false, index++))
                add(RadioStation(86, R.drawable.westfmlogo, "WEST FM", "94.9", "NAIROBI", linksList[86], false, false, index++))
                add(RadioStation(87, R.drawable.iftinfmlogo, "IFTIIN FM", "101.9", "NAIROBI", linksList[87], false, false, index++))
                add(RadioStation(88, R.drawable.mintofmlogo, "MINTO FM", "101.7", "NAIROBI", linksList[88], false, false, index++))
                add(RadioStation(89, R.drawable.bikapkoretradiologo, "BIKAPKORET RADIO", "98.2", "ELDORET", linksList[89], false, false, index++))
                add(RadioStation(90, R.drawable.muratafmlogo, "MURATA FM", "98.2", "ELDORET", linksList[90], false, false, index++))
                add(RadioStation(91, R.drawable.campusradiologo, "CAMPUS RADIO", "--.--", "NAIROBI", linksList[91], false, false, index++))
                add(RadioStation(93, R.drawable.utheriradiologo, "UTHERI RADIO", "106.2", "NAIROBI", linksList[93], false, false, index++))
                add(RadioStation(94, R.drawable.mugambowamugikuyulogo, "MUGAMBO WA MUGIKUYU", "--.--", "NAIROBI", linksList[94], false, false, index++))
                add(RadioStation(95, R.drawable.mwakifmlogo, "MWAKI FM", "--.--", "NAIROBI", linksList[95], false, false, index++))
                add(RadioStation(96, R.drawable.shilohradiologo, "SHILOH RADIO", "--.--", "NAIROBI", linksList[96], false, false, index++))
//                add(RadioStation(97, R.drawable.cambrigeradiologo, "CAMBRIDGE RADIO", "--.--", "NAIROBI", linksList[97], false, false, index++))
                add(RadioStation(98, R.drawable.angeladventistlogo, "ADVENTIST ANGELS", "90.0", "KISII", linksList[98], false, false, index++))
                add(RadioStation(99, R.drawable.utuuroradiologo, "UTUURO RADIO", "--.--", "NAIROBI", linksList[99], false, false, index++))
                add(RadioStation(100, R.drawable.maneneradiologo, "MANENE RADIO", "--.--", "KISUMU", linksList[100], false, false, index++))
                add(RadioStation(101, R.drawable.congasisfmlogo, "CONG'ASIS FM", "88.9", "NAIROBI", linksList[101], false, false, index++))
                add(RadioStation(102, R.drawable.northriftradiologo, "NORTHRIFT RADIO", "104.5", "KAPENGURIA", linksList[102], false, false, index++))
                add(RadioStation(103, R.drawable.relaxradiologo, "RELAX RADIO", "103.0", "NAIROBI", linksList[103], false, false, index++))
                add(RadioStation(104, R.drawable.smashjamradiologo, "SMASH JAM RADIO", "99.0", "NAKURU", linksList[104], false, false, index++))
                add(RadioStation(105, R.drawable.getufmlogo, "GETU RADIO", "87.6", "MERU", linksList[105], false, false, index++))
                add(RadioStation(106, R.drawable.kokwofmlogo, "KOKWO FM", "100.1", "KAPENGURIA", linksList[106], false, false, index++))
                add(RadioStation(107, R.drawable.mumbofmlogo, "MUMBO FM", "90.2", "BUNGOMA", linksList[107], false, false, index++))
                add(RadioStation(108, R.drawable.tandazafmlogo, "TANDAZA FM", "103.7", "BUNGOMA", linksList[108], false, false, index++))
                add(RadioStation(109, R.drawable.mixxradio560logo, "560 MIXX RADIO", "560kHz", "NAIROBI", linksList[109], false, false, index++))
                add(RadioStation(110, R.drawable.christianradiologo560, "560 CHRISTIAN RADIO", "560kHz", "NAIROBI", linksList[110], false, false, index++))
                add(RadioStation(111, R.drawable.powercountrylogo560, "560 POWER COUNTRY", "560kHz", "NAIROBI", linksList[111], false, false, index++))
                add(RadioStation(225, R.drawable.muthingifmlogo, "MUTHINGI FM", "--.--", "NAIROBI", linksList[225], false, false, index++))
                add(RadioStation(112, R.drawable.centralfmlogo, "CENTRAL FM", "97.1", "NANYUKI", linksList[112], false, false, index++))
                add(RadioStation(113, R.drawable.mayiengaradiologo, "MAYIENGA FM", "93.5", "BUNGOMA", linksList[113], false, false, index++))
                add(RadioStation(114, R.drawable.kitwekradiologo, "KITWEK RADIO", "92.9", "NAIROBI", linksList[114], false, false, index++))
                add(RadioStation(115, R.drawable.mwaturadiologo, "MWATU RADIO", "93.1", "MACHAKOS", linksList[115], false, false, index++))
                add(RadioStation(116, R.drawable.ingofmlogo, "INGO FM", "100.5", "NAIROBI", linksList[116], false, false, index++))
                add(RadioStation(117, R.drawable.powerfmlogo, "POWER FM", "--.--", "NAIROBI", linksList[117], false, false, index++))
                add(RadioStation(118, R.drawable.makinikaradiologo, "MAKINIKA RADIO", "--.--", "NAIROBI", linksList[118], false, false, index++))
                add(RadioStation(119, R.drawable.bloomradiologo, "BLOOM RADIO", "--.--", "NAIROBI", linksList[119], false, false, index++))
                add(RadioStation(120, R.drawable.rainbowradiologo, "RAINBOW RADIO", "---.--", "NAIROBI", linksList[120], false, false, index++))
                add(RadioStation(121, R.drawable.togotanefmlogo, "TOGOTANE FM", "88.3", "NAIROBI", linksList[121], false, false, index++))
                add(RadioStation(122, R.drawable.eretofmlogo, "ERETO FM", "--.--", "NYERI", linksList[122], false, false, index++))
                add(RadioStation(123, R.drawable.midzifmlogo, "MIDZI FM", "100.5", "MALINDI", linksList[123], false, false, index++))
                add(RadioStation(124, R.drawable.radio44logo, "RADIO 44", "91.6", "NAIROBI", linksList[124], false, false, index++))
                add(RadioStation(125, R.drawable.sayakiradiologo, "SAYAKI RADIO", "--.--", "NYERI", linksList[125], false, false, index++))
                add(RadioStation(126, R.drawable.radiosafarilogo, "RADIO SAFARI", "87.9", "KITALE", linksList[126], false, false, index++))
                add(RadioStation(227, R.drawable.berurfmlogo, "BERUR FM", "96.7", "NAIROBI", linksList[227], false, false, index++))
                add(RadioStation(127, R.drawable.radiofahamulogo, "RADIO FAHAMU", "--.--", "NAIROBI", linksList[127], false, false, index++))
                // add(RadioStation(128, R.drawable.mecolfmlogo, "MECOL FM", "--.--", "NAIROBI", linksFromTxt[128], false, false, index++))
                add(RadioStation(129, R.drawable.radio254logo, "RADIO 254", "--.--", "NAIROBI", linksList[129], false, false, index++))
                add(RadioStation(130, R.drawable.varchradiologo, "VARCH RADIO", "--.--", "ELDORET", linksList[130], false, false, index++))
                add(RadioStation(205, R.drawable.radiovunalogo, "RADIO VUNA", "102.0", "KISII", linksList[205], false, false, index++))
                add(RadioStation(131, R.drawable.tonziradiologo, "TONZI RADIO", "--.--", "NAIROBI", linksList[131], false, false, index++))
//                add(RadioStation(132, R.drawable.ifmlogo, "IFM PARTY STATION", "--.--", "NAIROBI", linksList[132], false, false, index++))
                add(RadioStation(133, R.drawable.elwaicenterfmlogo, "ELWAI CENTER FM", "--.--", "SUSWA", linksList[133], false, false, index++))
                add(RadioStation(134, R.drawable.countrypridefmlogo, "COUNTRY PRIDE FM", "--.--", "NAIROBI", linksList[134], false, false, index++))
//                add(RadioStation(135, R.drawable.musicjunkieslogo, "MUSICJUNKIES FM", "--.--", "NAIROBI", linksList[135], false, false, index++))
                add(RadioStation(136, R.drawable.smoothjazz560logo, "560 SMOOTHJAZZ", "--.--", "NAIROBI", linksList[136], false, false, index++))
                add(RadioStation(137, R.drawable.lightfmlogo, "LIGHT FM", "--.--", "NAIROBI", linksList[137], false, false, index++))
                add(RadioStation(138, R.drawable.icedfmlogo, "ICED RADIO", "--.--", "NAIROBI", linksList[138], false, false, index++))
                add(RadioStation(139, R.drawable.geeradiologo, "GEE RADIO", "--.--", "NAIROBI", linksList[139], false, false, index++))
                add(RadioStation(140, R.drawable.tulwoobkoonyradiologo, "TULWOOBKOONY RADIO", "--.--", "NAIROBI", linksList[140], false, false, index++))
                add(RadioStation(141, R.drawable.hootersfmlogo, "HOOTERS FM", "--.--", "NAIROBI", linksList[141], false, false, index++))
                add(RadioStation(142, R.drawable.kufurahiafmlogo, "KAFURAHA FM", "--.--", "NAIROBI", linksList[142], false, false, index++))
                add(RadioStation(143, R.drawable.hoodradiologo, "HOOD RADIO", "--.--", "NAIROBI", linksList[143], false, false, index++))
                add(RadioStation(144, R.drawable.abundanceradio, "ABUNDANCE RADIO", "--.--", "NAIROBI", linksList[144], false, false, index++))
                add(RadioStation(145, R.drawable.aipcalogo, "AIPCA RADIO", "--.--", "NAIROBI", linksList[145], false, false, index++))
                add(RadioStation(146, R.drawable.msenangufmlogo, "MSENANGU FM", "99.5", "MOMBASA", linksList[146], false, false, index++))
//                add(RadioStation(147, R.drawable.fynradiologo, "FYN RADIO", "--.--", "NAIROBI", linksList[147], false, false, index++))
//                add(RadioStation(148, R.drawable.xaticfmlogo, "XATIC FM", "--.--", "NAIROBI", linksList[148], false, false, index++))
                add(RadioStation(149, R.drawable.tusmofmlogo, "TUSMO FM", "--.--", "NAIROBI", linksList[149], false, false, index++))
                add(RadioStation(150, R.drawable.radioshahidilogo, "RADIO SHAHIDI", "91.7", "ISIOLO", linksList[150], false, false, index++))
                add(RadioStation(151, R.drawable.pemiradiologo, "PEMI RADIO", "96.1", "NAIROBI", linksList[151], false, false, index++))
//                add(RadioStation(152, R.drawable.freshfmlogo, "FRESH FM", "--.--", "NAIROBI", linksList[152], false, false, index++))
                add(RadioStation(153, R.drawable.hypemagnetradiologo, "HYPEMAGNET RADIO", "--.--", "NAIROBI", linksList[153], false, false, index++))
//                add(RadioStation(154, R.drawable.mindimoradiologo, "MIDNIMO RADIO", "--.--", "NAIROBI", linksList[154], false, false, index++))
                add(RadioStation(155, R.drawable.preachgospelradiologo, "PREACHGOSPEL", "--.--", "KISUMU", linksList[155], false, false, index++))
                add(RadioStation(156, R.drawable.radiomikayilogo, "RADIO MIKAYI", "88.8", "HOMABAY", linksList[156], false, false, index++))
                add(RadioStation(157, R.drawable.konyonfmlogo, "KONYON FM", "--.--", "KERICHO", linksList[157], false, false, index++))
                add(RadioStation(158, R.drawable.pgradiologo, "PG RADIO", "--.--", "KISUMU", linksList[158], false, false, index++))
//                add(RadioStation(159, R.drawable.aluochrisradiologo, "ALUOCHRIS RADIO", "--.--", "KISUMU", linksList[159], false, false, index++))
//                add(RadioStation(160, R.drawable.doitordoitfmlogo, "DOITORDOIT", "--.--", "MOMBASA", linksList[160], false, false, index++))
                add(RadioStation(161, R.drawable.doctorsexplainlogo, "DOCTORS EXPLAIN", "--.--", "NAIROBI", linksList[161], false, false, index++))
                add(RadioStation(162, R.drawable.edenmediaradiologo, "EDEN MEDIA", "--.--", "NAIROBI", linksList[162], false, false, index++))
//                add(RadioStation(163, R.drawable.xpressradiologo, "XPRESS RADIO", "102.9", "NAIROBI", linksList[163], false, false, index++))
                add(RadioStation(164, R.drawable.rasstyleradiologo, "RASSTYLE RADIO", "--.--", "NAIROBI", linksList[164], false, false, index++))
                add(RadioStation(165, R.drawable.optimumradiologo, "OPTIMUM RADIO", "--.--", "NAIROBI", linksList[165], false, false, index++))
                add(RadioStation(166, R.drawable.radiobarazalogo, "RADIO BARAZA", "--.--", "NAIROBI", linksList[166], false, false, index++))
//                add(RadioStation(167, R.drawable.radiopunchline, "RADIO PUNCHLINE", "--.--", "NAIROBI", linksList[167], false, false, index++))
//                add(RadioStation(168, R.drawable.gituambafmlogo, "GITUAMBA FM", "98.2MHz", "NAIROBI", linksList[168], false, false, index++))
                add(RadioStation(169, R.drawable.daradiologo, "DA RADIO", "--.--", "NAIROBI", linksList[169], false, false, index++))
                add(RadioStation(170, R.drawable.uncutradiologo, "UNCUT RADIO", "--.--", "NAIROBI", linksList[170], false, false, index++))
                add(RadioStation(171, R.drawable.gracefmlogo, "GRACE FM", "--.--", "NAIROBI", linksList[171], false, false, index++))
                add(RadioStation(202, R.drawable.radiochichilogo, "RADIO CHICHI", "100.7", "BARINGO", linksList[202], false, false, index++))
                add(RadioStation(221, R.drawable.theophilusfmlogo, "THEOPHILUS FM", "--.--", "NAIROBI", linksList[221], false, false, index++))
                add(RadioStation(222, R.drawable.ebruradiologo, "EBRU RADIO", "89.7", "MANDERA", linksList[222], false, false, index++))
                add(RadioStation(172, R.drawable.vybesradiologo, "VYBES RADIO", "104.5", "NAIROBI", linksList[172], false, false, index++))
                add(RadioStation(173, R.drawable.starfmlogo, "STAR FM", "105.9", "NAIROBI", linksList[173], false, false, index++))
                add(RadioStation(174, R.drawable.mwangazawanenofmlogo, "MWANGAZA WA NENO FM", "--.--", "NAIROBI", linksList[174], false, false, index++))
                add(RadioStation(175, R.drawable.thequestradiologo, "THEQUEST RADIO", "--.--", "NAIROBI", linksList[175], false, false, index++))
                add(RadioStation(176, R.drawable.radioasuronlogo, "RADIO ASURON", "--.--", "NAIROBI", linksList[176], false, false, index++))
                add(RadioStation(177, R.drawable.ruimbofmlogo, "RUIMBO FM", "--.--", "NAIROBI", linksList[177], false, false, index++))
                add(RadioStation(178, R.drawable.safinaradiologo, "SAFINA RADIO", "--.--", "NAIROBI", linksList[178], false, false, index++))
                add(RadioStation(179, R.drawable.sayarefmlogo, "SAYARE FM", "--.--", "NAIROBI", linksList[179], false, false, index++))
                add(RadioStation(180, R.drawable.prasieradiologo, "PRAISE RADIO", "--.--", "NAIROBI", linksList[180], false, false, index++))
                add(RadioStation(181, R.drawable.tognofm, "TOGNO FM", "--.--", "NAIROBI", linksList[181], false, false, index++))
                add(RadioStation(182, R.drawable.moronigospellogo, "MORONI GOSPEL", "--.--", "NAIROBI", linksList[182], false, false, index++))
                add(RadioStation(183, R.drawable.mwanaspotifmlogo, "MWANASPORTI FM", "--.--", "NAIROBI", linksList[183], false, false, index++))
                add(RadioStation(184, R.drawable.touchradiologo, "TOUCH RADIO", "--.--", "NAIROBI", linksList[184], false, false, index++))
                add(RadioStation(185, R.drawable.uigithaniofmlogo, "UIGITHANIO FM", "--.--", "NAIROBI", linksList[185], false, false, index++))
                add(RadioStation(186, R.drawable.radioamanilogo, "RADIO AMANI", "--.--", "NAIROBI", linksList[186], false, false, index++))
                add(RadioStation(187, R.drawable.ksmradiologo, "KSM RADIO", "--.--", "NAIROBI", linksList[187], false, false, index++))
                add(RadioStation(188, R.drawable.dapstreamradiologo, "DAPSTREAM RADIO", "--.--", "NAIROBI", linksList[188], false, false, index++))
                add(RadioStation(189, R.drawable.engelosradiologo, "ENGELOS RADIO", "--.--", "NAIROBI", linksList[189], false, false, index++))
                add(RadioStation(190, R.drawable.semafmlogo, "SEMA FM", "98.3", "NAIROBI", linksList[190], false, false, index++))
                add(RadioStation(191, R.drawable.kochfmlogo, "KOCH FM", "99.9", "NAIROBI", linksList[191], false, false, index++))
//                add(RadioStation(192, R.drawable.tsfmlogo, "TS FM", "--.--", "NAIROBI", linksList[192], false, false, index++))
//                add(RadioStation(193, R.drawable.nworksradiologo, "NWORKS RADIO", "--.--", "NAIROBI", linksList[193], false, false, index++))
                add(RadioStation(194, R.drawable.serianfmlogo, "SERIAN FM", "--.--", "NAIROBI", linksList[194], false, false, index++))
                add(RadioStation(195, R.drawable.radiomlimalogo, "RADIO MLIMA", "--.--", "NAIROBI", linksList[195], false, false, index++))
                add(RadioStation(196, R.drawable.ggvfmlogo, "GGV FM", "97.1", "MERU", linksList[196], false, false, index++))
                add(RadioStation(197, R.drawable.popoteradiologo, "POPOTE RADIO", "--.--", "NAIROBI", linksList[197], false, false, index++))
                add(RadioStation(198, R.drawable.radiotumainilogo, "RADIO TUMAINI", "93.0", "NAIROBI", linksList[198], false, false, index++))
                add(RadioStation(199, R.drawable.badidearadiologo, "BAD IDEA RADIO", "--.--", "NAIROBI", linksList[199], false, false, index++))
                add(RadioStation(200, R.drawable.diplomatradiologo, "DIPLOMAT RADIO", "--.--", "NAIROBI", linksList[200], false, false, index++))
                add(RadioStation(201, R.drawable.habeshingamusiclogo, "HABESHINGA MUSIC", "--.--", "NAIROBI", linksList[201], false, false, index++))
            }
            return radioStationsList
        }
    }
}
