package com.smoothradio.radio.feature.radiolist.util

import com.smoothradio.radio.core.domain.model.RadioStation

/**
 * Helper class for managing radio stations.
 *
 * This class provides utility functions related to radio station data,
 * such as creating a list of predefined radio stations and merging it
 * with locally stored station data (e.g., favorites, currently playing).
 */
class RadioStationsHelper {
    companion object {
        fun createRadioStations(linksList: List<String>): List<RadioStation> {
            val radioStationsList = mutableListOf<RadioStation>().apply {
                var index = 0 // Initialize the order index

                add(RadioStation(0, "HOPE FM", "93.3", "NAIROBI", linksList.getOrNull(0) ?: "", false, false, index++))
                add(RadioStation(1, "SOUNDCITY RADIO", "88.5", "NAIROBI", linksList.getOrNull(1) ?: "", false, false, index++))
                add(RadioStation(2, "KISS FM", "100.3", "NAIROBI", linksList.getOrNull(2) ?: "", false, false, index++))
                add(RadioStation(228, "RADIO 47", "103.0", "NAIROBI", linksList.getOrNull(228) ?: "", false, false, index++))
                add(RadioStation(3, "NRG RADIO", "97.1", "NAIROBI", linksList.getOrNull(3) ?: "", false, false, index++))
                add(RadioStation(203, "RADIO CITIZEN", "106.7", "NAIROBI", linksList.getOrNull(203) ?: "", false, false, index++))
                add(RadioStation(4, "INOORO FM", "98.9", "NAIROBI", linksList.getOrNull(4) ?: "", false, false, index++))
//                 add(RadioStation(206,"NJATA FM","97.2","NAIROBI",linksFromTxt.getOrNull(206) ?: "", false, false, index++))
                add(RadioStation(5, "CHOICE RADIO", "87.7", "NAIROBI", linksList.getOrNull(5) ?: "", false, false, index++))
                add(RadioStation(6, "HOT 96", "96.0", "NAIROBI", linksList.getOrNull(6) ?: "", false, false, index++))
                add(RadioStation(7, "HOMEBOYS RADIO", "103.5", "NAIROBI", linksList.getOrNull(7) ?: "", false, false, index++))
                add(RadioStation(8, "CLASSIC 105", "105.2", "NAIROBI", linksList.getOrNull(8) ?: "", false, false, index++))
                add(RadioStation(9, "RADIO JAMBO", "97.5", "NAIROBI", linksList.getOrNull(9) ?: "", false, false, index++))
                add(RadioStation(26, "ROGUE RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(26) ?: "", false, false, index++))
                add(RadioStation(30, "TRACE FM", "95.3", "NAIROBI", linksList.getOrNull(30) ?: "", false, false, index++))
                add(RadioStation(10, "CORO FM", "99.5", "NAIROBI", linksList.getOrNull(10) ?: "", false, false, index++))
                add(RadioStation(11, "KAMEME FM", "101.1", "NAIROBI", linksList.getOrNull(11) ?: "", false, false, index++))
                add(RadioStation(12, "GHETTO RADIO", "89.5", "NAIROBI", linksList.getOrNull(12) ?: "", false, false, index++))
                add(RadioStation(13, "RADIO MAISHA", "102.7", "NAIROBI", linksList.getOrNull(13) ?: "", false, false, index++))
                add(RadioStation(14, "EASY FM", "96.3", "NAIROBI", linksList.getOrNull(14) ?: "", false, false, index++))
                add(RadioStation(15, "RAMOGI FM", "107.1", "NAIROBI", linksList.getOrNull(15) ?: "", false, false, index++))
                add(RadioStation(16, "EGESA FM", "98.6", "NAIROBI", linksList.getOrNull(16) ?: "", false, false, index++))
                add(RadioStation(17, "MULEMBE FM", "97.9", "NAIROBI", linksList.getOrNull(17) ?: "", false, false, index++))
                add(RadioStation(18, "MUSYI FM", "102.2", "NAIROBI", linksList.getOrNull(18) ?: "", false, false, index++))
                add(RadioStation(19, "CHAMGEI FM", "95.0", "NAIROBI", linksList.getOrNull(19) ?: "", false, false, index++))
                add(RadioStation(25, "KUBAMBA RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(25) ?: "", false, false, index++))
                add(RadioStation(27, "TRUTH FM", "90.7", "NAIROBI", linksList.getOrNull(27) ?: "", false, false, index++))
                add(RadioStation(28, "FAMILY RADIO", "103.9", "NAIROBI", linksList.getOrNull(28) ?: "", false, false, index++))
                add(RadioStation(29, "JESUSISLORD RADIO", "105.3", "NAKURU", linksList.getOrNull(29) ?: "", false, false, index++))
                add(RadioStation(31, "SMOOTH FM", "105.5", "NAIROBI", linksList.getOrNull(31) ?: "", false, false, index++))
                add(RadioStation(32, "KIGOOCO FM", "98.6", "NAIROBI", linksList.getOrNull(32) ?: "", false, false, index++))
                add(RadioStation(38, "KENYA DIASPORA RADIO", "ONLINE", "ALABAMA", linksList.getOrNull(38) ?: "", false, false, index++))
                add(RadioStation(33, "MBCI RADIO", "89.5", "NAKURU", linksList.getOrNull(33) ?: "", false, false, index++))
//                add(RadioStation(224, "GFN FM", "90.1", "TURKANA", linksList.getOrNull(224) ?: "", false, false, index++))
                add(RadioStation(44, "NATION FM", "96.3", "NAIROBI", linksList.getOrNull(44) ?: "", false, false, index++))
                add(RadioStation(54, "CAPITAL FM", "98.4", "NAIROBI", linksList.getOrNull(54) ?: "", false, false, index++))
                add(RadioStation(231, "KWITU FM", "90.1", "MACHAKOS", linksList.getOrNull(231) ?: "", false, false, index++))
                add(RadioStation(41, "GUKENA FM", "92.8", "NAIROBI", linksList.getOrNull(41) ?: "", false, false, index++))
                add(RadioStation(20, "MUUGA FM", "94.2", "NAIROBI", linksList.getOrNull(20) ?: "", false, false, index++))
                add(RadioStation(21, "SULWE FM", "89.6", "NAIROBI", linksList.getOrNull(21) ?: "", false, false, index++))
                add(RadioStation(22, "WIMWARO FM", "93.0", "NAIROBI", linksList.getOrNull(22) ?: "", false, false, index++))
                add(RadioStation(23, "BAHARI FM", "90.4", "MOMBASA", linksList.getOrNull(23) ?: "", false, false, index++))
                add(RadioStation(24, "VUUKA FM", "95.4", "NAIROBI", linksList.getOrNull(24) ?: "", false, false, index++))
                add(RadioStation(92, "LUBAO FM", "102.2", "KAKAMEGA", linksList.getOrNull(92) ?: "", false, false, index++))
                add(RadioStation(34, "IQRA FM", "95.0", "NAIROBI", linksList.getOrNull(34) ?: "", false, false, index++))
                add(RadioStation(35, "PWANI FM", "103.1", "MOMBASA", linksList.getOrNull(35) ?: "", false, false, index++))
                add(RadioStation(36, "SAUTIYAPWANI FM", "94.2", "MOMBASA", linksList.getOrNull(36) ?: "", false, false, index++))
                add(RadioStation(37, "KBC RADIO TAIFA", "92.9", "NAIROBI", linksList.getOrNull(37) ?: "", false, false, index++))
                add(RadioStation(39, "TAACH FM", "95.1", "ELDORET", linksList.getOrNull(39) ?: "", false, false, index++))
                add(RadioStation(40, "EAST FM", "106.3", "NAIROBI", linksList.getOrNull(40) ?: "", false, false, index++))
                add(RadioStation(42, "KASS FM", "89.1", "NAIROBI", linksList.getOrNull(42) ?: "", false, false, index++))
                add(RadioStation(43, "SOUNDASIA RADIO", "88.0", "NAIROBI", linksList.getOrNull(43) ?: "", false, false, index++))
                add(RadioStation(45, "RADIO WAUMINI", "88.3", "NAIROBI", linksList.getOrNull(45) ?: "", false, false, index++))
                add(RadioStation(46, "BIBILIA HUSEMA FM", "96.7", "NAIROBI", linksList.getOrNull(46) ?: "", false, false, index++))
                add(RadioStation(47, "HERO RADIO", "99.0", "NAKURU", linksList.getOrNull(47) ?: "", false, false, index++))
                add(RadioStation(48, "MILELE FM", "104.8", "NAIROBI", linksList.getOrNull(48) ?: "", false, false, index++))
                add(RadioStation(207, "GETEMBE FM", "102.7", "KISII", linksList.getOrNull(207) ?: "", false, false, index++))
                add(RadioStation(208, "INKA FM", "93.7", "KISII", linksList.getOrNull(208) ?: "", false, false, index++))
                add(RadioStation(49, "RADIO KAYA", "93.1", "NAIROBI", linksList.getOrNull(49) ?: "", false, false, index++))
                add(RadioStation(50, "SPICE FM", "94.4", "NAIROBI", linksList.getOrNull(50) ?: "", false, false, index++))
                add(RadioStation(51, "BARAKA FM", "95.5", "MOMBASA", linksList.getOrNull(51) ?: "", false, false, index++))
                add(RadioStation(52, "RADIO INJILI", "103.7", "KERICHO", linksList.getOrNull(52) ?: "", false, false, index++))
                add(RadioStation(53, "ATHIANI FM", "99.2", "NAIROBI", linksList.getOrNull(53) ?: "", false, false, index++))
                add(RadioStation(55, "BEATLOCK RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(55) ?: "", false, false, index++))
                add(RadioStation(56, "PEARL XTRA FM", "ONLINE", "NAIROBI", linksList.getOrNull(56) ?: "", false, false, index++))
                add(RadioStation(57, "THE UPPERROOM FM", "ONLINE", "NAIROBI", linksList.getOrNull(57) ?: "", false, false, index++))
                add(RadioStation(58, "LULU FM", "91.0", "MOMBASA", linksList.getOrNull(58) ?: "", false, false, index++))
                add(RadioStation(59, "PEARL RADIO", "96.9", "NAIROBI", linksList.getOrNull(59) ?: "", false, false, index++))
                add(RadioStation(60, "IMANI RADIO", "88.8", "KITALE", linksList.getOrNull(60) ?: "", false, false, index++))
                add(RadioStation(61, "LIONAFRIQ RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(61) ?: "", false, false, index++))
                add(RadioStation(211, "NRG HIPHOP", "ONLINE", "NAIROBI", linksList.getOrNull(211) ?: "", false, false, index++))
                add(RadioStation(212, "NRG DANCEHALL", "ONLINE", "NAIROBI", linksList.getOrNull(212) ?: "", false, false, index++))
                add(RadioStation(213, "NRG GOSPEL", "ONLINE", "NAIROBI", linksList.getOrNull(213) ?: "", false, false, index++))
                add(RadioStation(214, "NRG AFROBEATS", "ONLINE", "NAIROBI", linksList.getOrNull(214) ?: "", false, false, index++))
                add(RadioStation(215, "NRG MIXOLOGY", "ONLINE", "NAIROBI", linksList.getOrNull(215) ?: "", false, false, index++))
                add(RadioStation(216, "NRG RNB", "ONLINE", "NAIROBI", linksList.getOrNull(216) ?: "", false, false, index++))
                add(RadioStation(217, "NRG JAZZ", "ONLINE", "NAIROBI", linksList.getOrNull(217) ?: "", false, false, index++))
                add(RadioStation(204, "LONGA RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(204) ?: "", false, false, index++))
                add(RadioStation(226, "KAYU FM", "91.0", "NAIROBI", linksList.getOrNull(226) ?: "", false, false, index++))
                add(RadioStation(62, "FLAMINGO FM", "93.7", "NAKURU", linksList.getOrNull(62) ?: "", false, false, index++))
//                add(RadioStation(63, "PILIPILI FM", "99.5", "NAIROBI", linksList.getOrNull(63) ?: "", false, false, index++))
                add(RadioStation(209, "KERIO RADIO", "87.6", "BARINGO", linksList.getOrNull(209) ?: "", false, false, index++))
                add(RadioStation(210, "TAUSI FM", "ONLINE", "NAIROBI", linksList.getOrNull(210) ?: "", false, false, index++))
                add(RadioStation(229, "HILLSIDE FM", "ONLINE", "NAIROBI", linksList.getOrNull(229) ?: "", false, false, index++))
                add(RadioStation(230, "PEFA RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(230) ?: "", false, false, index++))
                add(RadioStation(64, "MAYIAN FM", "100.7", "NAROK", linksList.getOrNull(64) ?: "", false, false, index++))
                add(RadioStation(65, "MERU FM", "100.3", "MERU", linksList.getOrNull(65) ?: "", false, false, index++))
                add(RadioStation(66, "EMOO FM", "104.2", "NAIROBI", linksList.getOrNull(66) ?: "", false, false, index++))
                add(RadioStation(223, "MUTONGOI FM", "103.3", "KITUI", linksList.getOrNull(223) ?: "", false, false, index++))
                add(RadioStation(218, "MWANGO FM", "97.5", "NAIROBI", linksList.getOrNull(218) ?: "", false, false, index++))
                add(RadioStation(219, "NOSIM FM", "90.5", "NAIROBI", linksList.getOrNull(219) ?: "", false, false, index++))
                add(RadioStation(220, "OSIEPE FM", "96.8", "SIAYA", linksList.getOrNull(220) ?: "", false, false, index++))
                add(RadioStation(67, "RADIO SALAAM", "90.7", "MOMBASA", linksList.getOrNull(67) ?: "", false, false, index++))
                add(RadioStation(68, "RADIO RAHMA", "91.5", "MOMBASA", linksList.getOrNull(68) ?: "", false, false, index++))
//                add(RadioStation(69, "ASYLUM RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(69) ?: "", false, false, index++))
                add(RadioStation(70, "KBC ENGLISH SERVICE", "95.6", "NAIROBI", linksList.getOrNull(70) ?: "", false, false, index++))
                add(RadioStation(71, "MBAITU FM", "92.5", "MACHAKOS", linksList.getOrNull(71) ?: "", false, false, index++))
                add(RadioStation(72, "RADIO MARIA", "90.0", "NAIROBI", linksList.getOrNull(72) ?: "", false, false, index++))
                add(RadioStation(73, "UPENDO RADIO", "89.4", "ELDORET", linksList.getOrNull(73) ?: "", false, false, index++))
                add(RadioStation(74, "HIPHOPGIN", "ONLINE", "NAIROBI", linksList.getOrNull(74) ?: "", false, false, index++))
                add(RadioStation(75, "HIPHOP DAILY", "97.5", "NAIROBI", linksList.getOrNull(75) ?: "", false, false, index++))
                add(RadioStation(79, "R FM", "99.9", "LIMURU", linksList.getOrNull(79) ?: "", false, false, index++))
                add(RadioStation(76, "TULIZA FM", "94.2", "MERU", linksList.getOrNull(76) ?: "", false, false, index++))
                add(RadioStation(77, "KIHOOTO FM", "91.2", "NAIROBI", linksList.getOrNull(77) ?: "", false, false, index++))
                add(RadioStation(78, "KISII FM", "94.1", "NAIROBI", linksList.getOrNull(78) ?: "", false, false, index++))
                add(RadioStation(80, "SEITO FM", "100.3", "NAIROBI", linksList.getOrNull(80) ?: "", false, false, index++))
                add(RadioStation(81, "SIFA FM", "101.2", "MARSABIT", linksList.getOrNull(81) ?: "", false, false, index++))
                add(RadioStation(82, "COUNTY FM", "90.3", "KITUI", linksList.getOrNull(82) ?: "", false, false, index++))
                add(RadioStation(83, "SIDAI FM", "103.5", "NAROK", linksList.getOrNull(83) ?: "", false, false, index++))
                add(RadioStation(84, "RADIO NEEMA", "ONLINE", "NAIROBI", linksList.getOrNull(84) ?: "", false, false, index++))
                add(RadioStation(85, "RADIO SIMBA", "93.1", "BUNGOMA", linksList.getOrNull(85) ?: "", false, false, index++))
                add(RadioStation(86, "WEST FM", "94.9", "NAIROBI", linksList.getOrNull(86) ?: "", false, false, index++))
                add(RadioStation(87, "IFTIIN FM", "101.9", "NAIROBI", linksList.getOrNull(87) ?: "", false, false, index++))
                add(RadioStation(88, "MINTO FM", "101.7", "NAIROBI", linksList.getOrNull(88) ?: "", false, false, index++))
                add(RadioStation(89, "BIKAPKORET RADIO", "98.2", "ELDORET", linksList.getOrNull(89) ?: "", false, false, index++))
                add(RadioStation(90, "MURATA FM", "98.2", "ELDORET", linksList.getOrNull(90) ?: "", false, false, index++))
                add(RadioStation(91, "CAMPUS RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(91) ?: "", false, false, index++))
                add(RadioStation(93, "UTHERI RADIO", "106.2", "NAIROBI", linksList.getOrNull(93) ?: "", false, false, index++))
                add(RadioStation(94, "MUGAMBO WA MUGIKUYU", "ONLINE", "NAIROBI", linksList.getOrNull(94) ?: "", false, false, index++))
                add(RadioStation(95, "MWAKI FM", "ONLINE", "NAIROBI", linksList.getOrNull(95) ?: "", false, false, index++))
                add(RadioStation(96, "SHILOH RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(96) ?: "", false, false, index++))
//                add(RadioStation(97, "CAMBRIDGE RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(97) ?: "", false, false, index++))
                add(RadioStation(98, "ADVENTIST ANGELS", "90.0", "KISII", linksList.getOrNull(98) ?: "", false, false, index++))
                add(RadioStation(99, "UTUURO RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(99) ?: "", false, false, index++))
                add(RadioStation(100, "MANENE RADIO", "ONLINE", "KISUMU", linksList.getOrNull(100) ?: "", false, false, index++))
                add(RadioStation(101, "CONG'ASIS FM", "88.9", "NAIROBI", linksList.getOrNull(101) ?: "", false, false, index++))
                add(RadioStation(102, "NORTHRIFT RADIO", "104.5", "KAPENGURIA", linksList.getOrNull(102) ?: "", false, false, index++))
                add(RadioStation(103, "RELAX RADIO", "103.0", "NAIROBI", linksList.getOrNull(103) ?: "", false, false, index++))
                add(RadioStation(104, "SMASH JAM RADIO", "99.0", "NAKURU", linksList.getOrNull(104) ?: "", false, false, index++))
                add(RadioStation(105, "GETU RADIO", "87.6", "MERU", linksList.getOrNull(105) ?: "", false, false, index++))
                add(RadioStation(106, "KOKWO FM", "100.1", "KAPENGURIA", linksList.getOrNull(106) ?: "", false, false, index++))
                add(RadioStation(107, "MUMBO FM", "90.2", "BUNGOMA", linksList.getOrNull(107) ?: "", false, false, index++))
                add(RadioStation(108, "TANDAZA FM", "103.7", "BUNGOMA", linksList.getOrNull(108) ?: "", false, false, index++))
                add(RadioStation(109, "560 MIXX RADIO", "560kHz", "NAIROBI", linksList.getOrNull(109) ?: "", false, false, index++))
                add(RadioStation(110, "560 CHRISTIAN RADIO", "560kHz", "NAIROBI", linksList.getOrNull(110) ?: "", false, false, index++))
                add(RadioStation(111, "560 POWER COUNTRY", "560kHz", "NAIROBI", linksList.getOrNull(111) ?: "", false, false, index++))
                add(RadioStation(225, "MUTHINGI FM", "ONLINE", "NAIROBI", linksList.getOrNull(225) ?: "", false, false, index++))
                add(RadioStation(112, "CENTRAL FM", "97.1", "NANYUKI", linksList.getOrNull(112) ?: "", false, false, index++))
                add(RadioStation(113, "MAYIENGA FM", "93.5", "BUNGOMA", linksList.getOrNull(113) ?: "", false, false, index++))
                add(RadioStation(114, "KITWEK RADIO", "92.9", "NAIROBI", linksList.getOrNull(114) ?: "", false, false, index++))
                add(RadioStation(115, "MWATU RADIO", "93.1", "MACHAKOS", linksList.getOrNull(115) ?: "", false, false, index++))
                add(RadioStation(116, "INGO FM", "100.5", "NAIROBI", linksList.getOrNull(116) ?: "", false, false, index++))
                add(RadioStation(117, "POWER FM", "ONLINE", "NAIROBI", linksList.getOrNull(117) ?: "", false, false, index++))
                add(RadioStation(118, "MAKINIKA RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(118) ?: "", false, false, index++))
                add(RadioStation(119, "BLOOM RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(119) ?: "", false, false, index++))
                add(RadioStation(120, "RAINBOW RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(120) ?: "", false, false, index++))
                add(RadioStation(121, "TOGOTANE FM", "88.3", "NAIROBI", linksList.getOrNull(121) ?: "", false, false, index++))
                add(RadioStation(122, "ERETO FM", "ONLINE", "NYERI", linksList.getOrNull(122) ?: "", false, false, index++))
                add(RadioStation(123, "MIDZI FM", "100.5", "MALINDI", linksList.getOrNull(123) ?: "", false, false, index++))
                add(RadioStation(124, "RADIO 44", "91.6", "NAIROBI", linksList.getOrNull(124) ?: "", false, false, index++))
                add(RadioStation(125, "SAYAKI RADIO", "ONLINE", "NYERI", linksList.getOrNull(125) ?: "", false, false, index++))
                add(RadioStation(126, "RADIO SAFARI", "87.9", "KITALE", linksList.getOrNull(126) ?: "", false, false, index++))
                add(RadioStation(227, "BERUR FM", "96.7", "NAIROBI", linksList.getOrNull(227) ?: "", false, false, index++))
                add(RadioStation(127, "RADIO FAHAMU", "ONLINE", "NAIROBI", linksList.getOrNull(127) ?: "", false, false, index++))
                // add(RadioStation(128, "MECOL FM", "ONLINE", "NAIROBI", linksFromTxt.getOrNull(128) ?: "", false, false, index++))
                add(RadioStation(129, "RADIO 254", "ONLINE", "NAIROBI", linksList.getOrNull(129) ?: "", false, false, index++))
                add(RadioStation(130, "VARCH RADIO", "ONLINE", "ELDORET", linksList.getOrNull(130) ?: "", false, false, index++))
                add(RadioStation(205, "RADIO VUNA", "102.0", "KISII", linksList.getOrNull(205) ?: "", false, false, index++))
                add(RadioStation(131, "TONZI RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(131) ?: "", false, false, index++))
//                add(RadioStation(132, "IFM PARTY STATION", "ONLINE", "NAIROBI", linksList.getOrNull(132) ?: "", false, false, index++))
                add(RadioStation(133, "ELWAI CENTER FM", "ONLINE", "SUSWA", linksList.getOrNull(133) ?: "", false, false, index++))
                add(RadioStation(134, "COUNTRY PRIDE FM", "ONLINE", "NAIROBI", linksList.getOrNull(134) ?: "", false, false, index++))
//                add(RadioStation(135, "MUSICJUNKIES FM", "ONLINE", "NAIROBI", linksList.getOrNull(135) ?: "", false, false, index++))
                add(RadioStation(136, "560 SMOOTHJAZZ", "ONLINE", "NAIROBI", linksList.getOrNull(136) ?: "", false, false, index++))
                add(RadioStation(137, "LIGHT FM", "ONLINE", "NAIROBI", linksList.getOrNull(137) ?: "", false, false, index++))
                add(RadioStation(138, "ICED RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(138) ?: "", false, false, index++))
                add(RadioStation(139, "GEE RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(139) ?: "", false, false, index++))
                add(RadioStation(140, "TULWOOBKOONY RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(140) ?: "", false, false, index++))
                add(RadioStation(141, "HOOTERS FM", "ONLINE", "NAIROBI", linksList.getOrNull(141) ?: "", false, false, index++))
                add(RadioStation(142, "KAFURAHA FM", "ONLINE", "NAIROBI", linksList.getOrNull(142) ?: "", false, false, index++))
                add(RadioStation(143, "HOOD RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(143) ?: "", false, false, index++))
                add(RadioStation(144, "ABUNDANCE RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(144) ?: "", false, false, index++))
                add(RadioStation(145, "AIPCA RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(145) ?: "", false, false, index++))
                add(RadioStation(146, "MSENANGU FM", "99.5", "MOMBASA", linksList.getOrNull(146) ?: "", false, false, index++))
                add(RadioStation(149, "TUSMO FM", "ONLINE", "NAIROBI", linksList.getOrNull(149) ?: "", false, false, index++))
                add(RadioStation(150, "RADIO SHAHIDI", "91.7", "ISIOLO", linksList.getOrNull(150) ?: "", false, false, index++))
                add(RadioStation(151, "PEMI RADIO", "96.1", "NAIROBI", linksList.getOrNull(151) ?: "", false, false, index++))
                add(RadioStation(153, "HYPEMAGNET RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(153) ?: "", false, false, index++))
                add(RadioStation(155, "PREACHGOSPEL", "ONLINE", "KISUMU", linksList.getOrNull(155) ?: "", false, false, index++))
                add(RadioStation(156, "RADIO MIKAYI", "88.8", "HOMABAY", linksList.getOrNull(156) ?: "", false, false, index++))
                add(RadioStation(157, "KONYON FM", "ONLINE", "KERICHO", linksList.getOrNull(157) ?: "", false, false, index++))
                add(RadioStation(158, "PG RADIO", "ONLINE", "KISUMU", linksList.getOrNull(158) ?: "", false, false, index++))
                add(RadioStation(161, "DOCTORS EXPLAIN", "ONLINE", "NAIROBI", linksList.getOrNull(161) ?: "", false, false, index++))
                add(RadioStation(162, "EDEN MEDIA", "ONLINE", "NAIROBI", linksList.getOrNull(162) ?: "", false, false, index++))
                add(RadioStation(164, "RASTYLE RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(164) ?: "", false, false, index++))
                add(RadioStation(165, "OPTIMUM RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(165) ?: "", false, false, index++))
                add(RadioStation(166, "RADIO BARAZA", "ONLINE", "NAIROBI", linksList.getOrNull(166) ?: "", false, false, index++))
                add(RadioStation(169, "DA RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(169) ?: "", false, false, index++))
                add(RadioStation(170, "UNCUT RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(170) ?: "", false, false, index++))
                add(RadioStation(171, "GRACE FM", "ONLINE", "NAIROBI", linksList.getOrNull(171) ?: "", false, false, index++))
                add(RadioStation(202, "RADIO CHICHI", "100.7", "BARINGO", linksList.getOrNull(202) ?: "", false, false, index++))
                add(RadioStation(221, "THEOPHILUS FM", "ONLINE", "NAIROBI", linksList.getOrNull(221) ?: "", false, false, index++))
                add(RadioStation(222, "EBRU RADIO", "89.7", "MANDERA", linksList.getOrNull(222) ?: "", false, false, index++))
                add(RadioStation(172, "VYBES RADIO", "104.5", "NAIROBI", linksList.getOrNull(172) ?: "", false, false, index++))
                add(RadioStation(173, "STAR FM", "105.9", "NAIROBI", linksList.getOrNull(173) ?: "", false, false, index++))
                add(RadioStation(174, "MWANGAZA WA NENO FM", "ONLINE", "NAIROBI", linksList.getOrNull(174) ?: "", false, false, index++))
                add(RadioStation(175, "THEQUEST RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(175) ?: "", false, false, index++))
                add(RadioStation(176, "RADIO ASURON", "ONLINE", "NAIROBI", linksList.getOrNull(176) ?: "", false, false, index++))
                add(RadioStation(177, "RUIMBO FM", "ONLINE", "NAIROBI", linksList.getOrNull(177) ?: "", false, false, index++))
                add(RadioStation(178, "SAFINA RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(178) ?: "", false, false, index++))
                add(RadioStation(179, "SAYARE FM", "ONLINE", "NAIROBI", linksList.getOrNull(179) ?: "", false, false, index++))
                add(RadioStation(180, "PRAISE RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(180) ?: "", false, false, index++))
                add(RadioStation(181, "TOGNO FM", "ONLINE", "NAIROBI", linksList.getOrNull(181) ?: "", false, false, index++))
                add(RadioStation(182, "MORONI GOSPEL", "ONLINE", "NAIROBI", linksList.getOrNull(182) ?: "", false, false, index++))
                add(RadioStation(183, "MWANASPORTI FM", "ONLINE", "NAIROBI", linksList.getOrNull(183) ?: "", false, false, index++))
                add(RadioStation(184, "TOUCH RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(184) ?: "", false, false, index++))
                add(RadioStation(185, "UIGITHANIO FM", "ONLINE", "NAIROBI", linksList.getOrNull(185) ?: "", false, false, index++))
                add(RadioStation(186, "RADIO AMANI", "ONLINE", "NAIROBI", linksList.getOrNull(186) ?: "", false, false, index++))
                add(RadioStation(187, "KSM RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(187) ?: "", false, false, index++))
                add(RadioStation(188, "DAPSTREAM RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(188) ?: "", false, false, index++))
                add(RadioStation(189, "ENGELOS RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(189) ?: "", false, false, index++))
                add(RadioStation(190, "SEMA FM", "98.3", "NAIROBI", linksList.getOrNull(190) ?: "", false, false, index++))
                add(RadioStation(191, "KOCH FM", "99.9", "NAIROBI", linksList.getOrNull(191) ?: "", false, false, index++))
                add(RadioStation(194, "SERIAN FM", "ONLINE", "NAIROBI", linksList.getOrNull(194) ?: "", false, false, index++))
                add(RadioStation(195, "RADIO MLIMA", "ONLINE", "NAIROBI", linksList.getOrNull(195) ?: "", false, false, index++))
                add(RadioStation(196, "GGV FM", "97.1", "MERU", linksList.getOrNull(196) ?: "", false, false, index++))
                add(RadioStation(197, "POPOTE RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(197) ?: "", false, false, index++))
                add(RadioStation(198, "RADIO TUMAINI", "93.0", "NAIROBI", linksList.getOrNull(198) ?: "", false, false, index++))
                add(RadioStation(199, "BAD IDEA RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(199) ?: "", false, false, index++))
                add(RadioStation(200, "DIPLOMAT RADIO", "ONLINE", "NAIROBI", linksList.getOrNull(200) ?: "", false, false, index++))
                add(RadioStation(201, "HABESHINGA MUSIC", "ONLINE", "NAIROBI", linksList.getOrNull(201) ?: "", false, false, index++))
            }
            return radioStationsList
        }
    }
}
