package com.smoothradio.radio.core.ui;

import com.smoothradio.radio.R;
import com.smoothradio.radio.model.RadioStation;

import java.util.ArrayList;
import java.util.List;

public class RadioStationsHelper {
    public static List<RadioStation> createRadioStations(List<String> linksFromTxt) {
        List<RadioStation> radioStationsList = new ArrayList<>();

        radioStationsList.add(new RadioStation(R.drawable.hopefm, "HOPE FM", "93.3", "NAIROBI", linksFromTxt.get(0), 0));

        radioStationsList.add(new RadioStation(R.drawable.soundcityradiologo, "SOUNDCITY RADIO", "88.5", "NAIROBI", linksFromTxt.get(1), 1));
        radioStationsList.add(new RadioStation(R.drawable.kissfm, "KISS FM", "100.3", "NAIROBI", linksFromTxt.get(2), 2));
        radioStationsList.add(new RadioStation(R.drawable.radio47logo, "RADIO 47", "103.0", "NAIROBI", linksFromTxt.get(228), 228));
        radioStationsList.add(new RadioStation(R.drawable.nrg0, "NRG RADIO", "97.1", "NAIROBI", linksFromTxt.get(3), 3));
        radioStationsList.add(new RadioStation(R.drawable.radiocitizenlogo, "RADIO CITIZEN", "106.7", "NAIROBI", linksFromTxt.get(203), 203));
        radioStationsList.add(new RadioStation(R.drawable.inooro, "INOORO FM", "98.9", "NAIROBI", linksFromTxt.get(4), 4));
        //radioStationsList.add(new RadioStation(R.drawable.njatafmlogo,"NJATA FM","97.2","NAIROBI",linksFromTxt.get(206)));
        radioStationsList.add(new RadioStation(R.drawable.nrgchoiceradiologo, "CHOICE RADIO", "87.7", "NAIROBI", linksFromTxt.get(5), 5));

        radioStationsList.add(new RadioStation(R.drawable.hot96logo, "HOT 96", "96.0", "NAIROBI", linksFromTxt.get(6), 6));
        radioStationsList.add(new RadioStation(R.drawable.homeboys, "HOMEBOYS RADIO", "103.5", "NAIROBI", linksFromTxt.get(7), 7));
        radioStationsList.add(new RadioStation(R.drawable.classic105_logo, "CLASSIC 105", "105.2", "NAIROBI", linksFromTxt.get(8), 8));
        radioStationsList.add(new RadioStation(R.drawable.radiojambologo, "RADIO JAMBO", "97.5", "NAIROBI", linksFromTxt.get(9), 9));
        radioStationsList.add(new RadioStation(R.drawable.rogueradiologo, "ROGUE RADIO", "--.--", "NAIROBI", linksFromTxt.get(26), 26));
        radioStationsList.add(new RadioStation(R.drawable.tracefmlogo, "TRACE FM", "95.3", "NAIROBI", linksFromTxt.get(30), 30));
        radioStationsList.add(new RadioStation(R.drawable.corofmlogo, "CORO FM", "99.5", "NAIROBI", linksFromTxt.get(10), 10));
        radioStationsList.add(new RadioStation(R.drawable.kameme, "KAMEME FM", "101.1", "NAIROBI", linksFromTxt.get(11), 11));
        radioStationsList.add(new RadioStation(R.drawable.ghettoradiologo, "GHETTO RADIO", "89.5", "NAIROBI", linksFromTxt.get(12), 12));
        radioStationsList.add(new RadioStation(R.drawable.radiomaishalogo, "RADIO MAISHA", "102.7", "NAIROBI", linksFromTxt.get(13), 13));
        radioStationsList.add(new RadioStation(R.drawable.easyfmlogo, "EASY FM", "96.3", "NAIROBI", linksFromTxt.get(14), 14));
        radioStationsList.add(new RadioStation(R.drawable.ramogilogo, "RAMOGI FM", "107.1", "NAIROBI", linksFromTxt.get(15), 15));
        radioStationsList.add(new RadioStation(R.drawable.egesalogo, "EGESA FM", "98.6", "NAIROBI", linksFromTxt.get(16), 16));
        radioStationsList.add(new RadioStation(R.drawable.mulembelogo, "MULEMBE FM", "97.9", "NAIROBI", linksFromTxt.get(17), 17));
        radioStationsList.add(new RadioStation(R.drawable.musyilogo, "MUSYI FM", "102.2", "NAIROBI", linksFromTxt.get(18), 18));
        radioStationsList.add(new RadioStation(R.drawable.chamgeilogo, "CHAMGEI FM", "95.0", "NAIROBI", linksFromTxt.get(19), 19));
        radioStationsList.add(new RadioStation(R.drawable.kubambaradiologo, "KUBAMBA RADIO", "--.--", "NAIROBI", linksFromTxt.get(25), 25));
        radioStationsList.add(new RadioStation(R.drawable.truthfmlogo, "TRUTH FM", "90.7", "NAIROBI", linksFromTxt.get(27), 27));
        radioStationsList.add(new RadioStation(R.drawable.familyradiologo, "FAMILY RADIO", "103.9", "NAIROBI", linksFromTxt.get(28), 28));
        radioStationsList.add(new RadioStation(R.drawable.jesusislordradiologo, "JESUSISLORD RADIO", "105.3", "NAKURU", linksFromTxt.get(29), 29));
        radioStationsList.add(new RadioStation(R.drawable.xfmlogo, "SMOOTH FM", "105.5", "NAIROBI", linksFromTxt.get(31), 31));
        radioStationsList.add(new RadioStation(R.drawable.kigoocofmlogo, "KIGOOCO FM", "98.6", "NAIROBI", linksFromTxt.get(32), 32));
        radioStationsList.add(new RadioStation(R.drawable.kikuyudiasporaradiologo, "KENYA DIASPORA RADIO", "--.--", "ALABAMA", linksFromTxt.get(38), 38));
        radioStationsList.add(new RadioStation(R.drawable.mbciradiologo, "MBCI RADIO", "89.5", "NAKURU", linksFromTxt.get(33), 33));
        radioStationsList.add(new RadioStation(R.drawable.gfnradiologo, "GFN FM", "90.1", "TURKANA", linksFromTxt.get(224), 224));
        radioStationsList.add(new RadioStation(R.drawable.nationfmlogo, "NATION FM", "96.3", "NAIROBI", linksFromTxt.get(44), 44));
        radioStationsList.add(new RadioStation(R.drawable.capitalfmlogo, "CAPITAL FM", "98.4", "NAIROBI", linksFromTxt.get(54), 54));

        radioStationsList.add(new RadioStation(R.drawable.gukenafmlogo, "GUKENA FM", "92.8", "NAIROBI", linksFromTxt.get(41), 41));
        radioStationsList.add(new RadioStation(R.drawable.muugalogo, "MUUGA FM", "94.2", "NAIROBI", linksFromTxt.get(20), 20));
        radioStationsList.add(new RadioStation(R.drawable.sulwelogo, "SULWE FM", "89.6", "NAIROBI", linksFromTxt.get(21), 21));
        radioStationsList.add(new RadioStation(R.drawable.wimwarologo, "WIMWARO FM", "93.0", "NAIROBI", linksFromTxt.get(22), 22));
        radioStationsList.add(new RadioStation(R.drawable.baharilogo, "BAHARI FM", "90.4", "MOMBASA", linksFromTxt.get(23), 23));
        radioStationsList.add(new RadioStation(R.drawable.vuukalogo, "VUUKA FM", "95.4", "NAIROBI", linksFromTxt.get(24), 24));
        radioStationsList.add(new RadioStation(R.drawable.lubaofmlogo, "LUBAO FM", "102.2", "KAKAMEGA", linksFromTxt.get(92), 92));
        radioStationsList.add(new RadioStation(R.drawable.iqrafmlogo, "IQRA FM", "95.0", "NAIROBI", linksFromTxt.get(34), 34));

        radioStationsList.add(new RadioStation(R.drawable.pwanifmlogo, "PWANI FM", "103.1", "MOMBASA", linksFromTxt.get(35), 35));
        radioStationsList.add(new RadioStation(R.drawable.sautiyapwanifmlogo, "SAUTIYAPWANI FM", "94.2", "MOMBASA", linksFromTxt.get(36), 36));
        radioStationsList.add(new RadioStation(R.drawable.kbcradiotaifalogo, "KBC RADIO TAIFA", "92.9", "NAIROBI", linksFromTxt.get(37), 37));
        radioStationsList.add(new RadioStation(R.drawable.taachfmlogo, "TAACH FM", "95.1", "ELDORET", linksFromTxt.get(39), 39));
        radioStationsList.add(new RadioStation(R.drawable.eastfmlogo, "EAST FM", "106.3", "NAIROBI", linksFromTxt.get(40), 40));
        radioStationsList.add(new RadioStation(R.drawable.kassfmlogo, "KASS FM", "89.1", "NAIROBI", linksFromTxt.get(42), 42));
        radioStationsList.add(new RadioStation(R.drawable.soundasialogo, "SOUNDASIA RADIO", "88.0", "NAIROBI", linksFromTxt.get(43), 43));
        radioStationsList.add(new RadioStation(R.drawable.wauminilogo, "RADIO WAUMINI", "88.3", "NAIROBI", linksFromTxt.get(45), 45));

        radioStationsList.add(new RadioStation(R.drawable.bibiliahusemalogo, "BIBILIA HUSEMA FM", "96.7", "NAIROBI", linksFromTxt.get(46), 46));
        radioStationsList.add(new RadioStation(R.drawable.heroradiologo, "HERO RADIO", "99.0", "NAKURU", linksFromTxt.get(47), 47));
        radioStationsList.add(new RadioStation(R.drawable.milelefmlogo, "MILELE FM", "104.8", "NAIROBI", linksFromTxt.get(48), 48));
        radioStationsList.add(new RadioStation(R.drawable.getembefmlogo, "GETEMBE FM", "102.7", "KISII", linksFromTxt.get(207), 207));
        radioStationsList.add(new RadioStation(R.drawable.inkafmlogo, "INKA FM", "93.7", "KISII", linksFromTxt.get(208), 208));
        radioStationsList.add(new RadioStation(R.drawable.radiokayalogo, "RADIO KAYA", "93.1", "NAIROBI", linksFromTxt.get(49), 49));
        radioStationsList.add(new RadioStation(R.drawable.spicefmlogo, "SPICE FM", "94.4", "NAIROBI", linksFromTxt.get(50), 50));
        radioStationsList.add(new RadioStation(R.drawable.barakafmlogo, "BARAKA FM", "95.5", "MOMBASA", linksFromTxt.get(51), 51));
        radioStationsList.add(new RadioStation(R.drawable.radioinjililogo, "RADIO INJILI", "103.7", "KERICHO", linksFromTxt.get(52), 52));
        radioStationsList.add(new RadioStation(R.drawable.athianilogo, "ATHIANI FM", "99.2", "NAIROBI", linksFromTxt.get(53), 53));
        radioStationsList.add(new RadioStation(R.drawable.beatlocklogo, "BEATLOCK RADIO", "--.--", "NAIROBI", linksFromTxt.get(55), 55));
        radioStationsList.add(new RadioStation(R.drawable.pearlxtralogo, "PEARL XTRA FM", "--.--", "NAIROBI", linksFromTxt.get(56), 56));
        radioStationsList.add(new RadioStation(R.drawable.theupperroomlogo, "THE UPPERROOM FM", "--.--", "NAIROBI", linksFromTxt.get(57), 57));
        radioStationsList.add(new RadioStation(R.drawable.lulufmlogo, "LULU FM", "91.0", "MOMBASA", linksFromTxt.get(58), 58));
        radioStationsList.add(new RadioStation(R.drawable.pearlradiologo, "PEARL RADIO", "96.9", "NAIROBI", linksFromTxt.get(59), 59));

        radioStationsList.add(new RadioStation(R.drawable.imaniradiologo, "IMANI RADIO", "88.8", "KITALE", linksFromTxt.get(60), 60));
        radioStationsList.add(new RadioStation(R.drawable.lionafriqradiologo, "LIONAFRIQ RADIO", "--.--", "NAIROBI", linksFromTxt.get(61), 61));
        radioStationsList.add(new RadioStation(R.drawable.nrg_hiphop_logo, "NRG HIPHOP", "--.--", "NAIROBI", linksFromTxt.get(211), 211));
        radioStationsList.add(new RadioStation(R.drawable.nrg_dancehall_logo, "NRG DANCEHALL", "--.--", "NAIROBI", linksFromTxt.get(212), 212));
        radioStationsList.add(new RadioStation(R.drawable.nrg_gospel_logo, "NRG GOSPEL", "--.--", "NAIROBI", linksFromTxt.get(213), 213));
        radioStationsList.add(new RadioStation(R.drawable.nrg_afrobeats_logo, "NRG AFROBEATS", "--.--", "NAIROBI", linksFromTxt.get(214), 214));
        radioStationsList.add(new RadioStation(R.drawable.nrg_mixology_logo, "NRG MIXOLOGY", "--.--", "NAIROBI", linksFromTxt.get(215), 215));
        radioStationsList.add(new RadioStation(R.drawable.nrg_rnb_logo, "NRG RNB", "--.--", "NAIROBI", linksFromTxt.get(216), 216));
        radioStationsList.add(new RadioStation(R.drawable.nrg_jazz_logo, "NRG JAZZ", "--.--", "NAIROBI", linksFromTxt.get(217), 217));
        radioStationsList.add(new RadioStation(R.drawable.longaradiologo, "LONGA RADIO", "--.--", "NAIROBI", linksFromTxt.get(204), 204));
        radioStationsList.add(new RadioStation(R.drawable.kayufmlogo, "KAYU FM", "91.0", "NAIROBI", linksFromTxt.get(226), 226));
        radioStationsList.add(new RadioStation(R.drawable.flamingoradiologo, "FLAMINGO FM", "93.7", "NAKURU", linksFromTxt.get(62), 62));
        radioStationsList.add(new RadioStation(R.drawable.pilipilifmlogo, "PILIPILI FM", "99.5", "NAIROBI", linksFromTxt.get(63), 63));
        radioStationsList.add(new RadioStation(R.drawable.kerioradiologo, "KERIO RADIO", "87.6", "BARINGO", linksFromTxt.get(209), 209));
        radioStationsList.add(new RadioStation(R.drawable.tausifmlogo, "TAUSI FM", "--.--", "NAIROBI", linksFromTxt.get(210), 210));
        radioStationsList.add(new RadioStation(R.drawable.hillsidefmlogo, "HILLSIDE FM", "--.--", "NAIROBI", linksFromTxt.get(229), 229));
        radioStationsList.add(new RadioStation(R.drawable.pefaradoilogo, "PEFA RADIO", "--.--", "NAIROBI", linksFromTxt.get(230), 230));
        radioStationsList.add(new RadioStation(R.drawable.mayianfmlogo, "MAYIAN FM", "100.7", "NAROK", linksFromTxt.get(64), 64));
        radioStationsList.add(new RadioStation(R.drawable.merufmlogo, "MERU FM", "100.3", "MERU", linksFromTxt.get(65), 65));
        radioStationsList.add(new RadioStation(R.drawable.emoofmlogo, "EMOO FM", "104.2", "NAIROBI", linksFromTxt.get(66), 66));
        radioStationsList.add(new RadioStation(R.drawable.mutongoifmlogo, "MUTONGOI FM", "103.3", "KITUI", linksFromTxt.get(223), 223));
        radioStationsList.add(new RadioStation(R.drawable.mwagofmlogo, "MWANGO FM", "97.5", "NAIROBI", linksFromTxt.get(218), 218));
        radioStationsList.add(new RadioStation(R.drawable.nosimfmlogo, "NOSIM FM", "90.5", "NAIROBI", linksFromTxt.get(219), 219));
        radioStationsList.add(new RadioStation(R.drawable.osiepefmlogo, "OSIEPE FM", "96.8", "SIAYA", linksFromTxt.get(220), 220));
        radioStationsList.add(new RadioStation(R.drawable.radiosalaamlogo, "RADIO SALAAM", "90.7", "MOMBASA", linksFromTxt.get(67), 67));
        radioStationsList.add(new RadioStation(R.drawable.radiorahmalogo, "RADIO RAHMA", "91.5", "MOMBASA", linksFromTxt.get(68), 68));
        radioStationsList.add(new RadioStation(R.drawable.asylumradiologo, "ASYLUM RADIO", "--.--", "NAIROBI", linksFromTxt.get(69), 69));
        radioStationsList.add(new RadioStation(R.drawable.kbcenglishservicelogo, "KBC ENGLISH SERVICE", "95.6", "NAIROBI", linksFromTxt.get(70), 70));
        radioStationsList.add(new RadioStation(R.drawable.mbaitufmlogo, "MBAITU FM", "92.5", "MACHAKOS", linksFromTxt.get(71), 71));
        radioStationsList.add(new RadioStation(R.drawable.radio_maria, "RADIO MARIA", "90.0", "NAIROBI", linksFromTxt.get(72), 72));
        radioStationsList.add(new RadioStation(R.drawable.upendoradiologo, "UPENDO RADIO", "89.4", "ELDORET", linksFromTxt.get(73), 73));
        radioStationsList.add(new RadioStation(R.drawable.hiphopginlogo, "HIPHOPGIN", "--.--", "NAIROBI", linksFromTxt.get(74), 74));
        radioStationsList.add(new RadioStation(R.drawable.hiphopdailylogo, "HIPHOP DAILY", "97.5", "NAIROBI", linksFromTxt.get(75), 75));
        radioStationsList.add(new RadioStation(R.drawable.rfmlogo, "R FM", "99.9", "LIMURU", linksFromTxt.get(79), 79));
        radioStationsList.add(new RadioStation(R.drawable.tulizafmlogo, "TULIZA FM", "94.2", "MERU", linksFromTxt.get(76), 76));
        radioStationsList.add(new RadioStation(R.drawable.kihootofmlogo, "KIHOOTO FM", "91.2", "NAIROBI", linksFromTxt.get(77), 77));
        radioStationsList.add(new RadioStation(R.drawable.kisiifmlogo, "KISII FM", "94.1", "NAIROBI", linksFromTxt.get(78), 78));
        radioStationsList.add(new RadioStation(R.drawable.seitofmlogo, "SEITO FM", "100.3", "NAIROBI", linksFromTxt.get(80), 80));
        radioStationsList.add(new RadioStation(R.drawable.sifafmlogo, "SIFA FM", "101.2", "MARSABIT", linksFromTxt.get(81), 81));
        radioStationsList.add(new RadioStation(R.drawable.countyfmlogo, "COUNTY FM", "90.3", "KITUI", linksFromTxt.get(82), 82));
        radioStationsList.add(new RadioStation(R.drawable.sidaifmlogo, "SIDAI FM", "103.5", "NAROK", linksFromTxt.get(83), 83));
        radioStationsList.add(new RadioStation(R.drawable.radioneemalogo, "RADIO NEEMA", "--.--", "NAIROBI", linksFromTxt.get(84), 84));
        radioStationsList.add(new RadioStation(R.drawable.radiosimbalogo, "RADIO SIMBA", "93.1", "BUNGOMA", linksFromTxt.get(85), 85));
        radioStationsList.add(new RadioStation(R.drawable.westfmlogo, "WEST FM", "94.9", "NAIROBI", linksFromTxt.get(86), 86));
        radioStationsList.add(new RadioStation(R.drawable.iftinfmlogo, "IFTIIN FM", "101.9", "NAIROBI", linksFromTxt.get(87), 87));
        radioStationsList.add(new RadioStation(R.drawable.mintofmlogo, "MINTO FM", "101.7", "NAIROBI", linksFromTxt.get(88), 88));
        radioStationsList.add(new RadioStation(R.drawable.bikapkoretradiologo, "BIKAPKORET RADIO", "98.2", "ELDORET", linksFromTxt.get(89), 89));
        radioStationsList.add(new RadioStation(R.drawable.muratafmlogo, "MURATA FM", "98.2", "ELDORET", linksFromTxt.get(90), 90));
        radioStationsList.add(new RadioStation(R.drawable.campusradiologo, "CAMPUS RADIO", "--.--", "NAIROBI", linksFromTxt.get(91), 91));
        radioStationsList.add(new RadioStation(R.drawable.utheriradiologo, "UTHERI RADIO", "106.2", "NAIROBI", linksFromTxt.get(93), 93));
        radioStationsList.add(new RadioStation(R.drawable.mugambowamugikuyulogo, "MUGAMBO WA MUGIKUYU", "--.--", "NAIROBI", linksFromTxt.get(94), 94));
        radioStationsList.add(new RadioStation(R.drawable.mwakifmlogo, "MWAKI FM", "--.--", "NAIROBI", linksFromTxt.get(95), 95));
        radioStationsList.add(new RadioStation(R.drawable.shilohradiologo, "SHILOH RADIO", "--.--", "NAIROBI", linksFromTxt.get(96), 96));
        radioStationsList.add(new RadioStation(R.drawable.cambrigeradiologo, "CAMBRIDGE RADIO", "--.--", "NAIROBI", linksFromTxt.get(97), 97));
        radioStationsList.add(new RadioStation(R.drawable.angeladventistlogo, "ADVENTIST ANGELS", "90.0", "KISII", linksFromTxt.get(98), 98));
        radioStationsList.add(new RadioStation(R.drawable.utuuroradiologo, "UTUURO RADIO", "--.--", "NAIROBI", linksFromTxt.get(99), 99));
        radioStationsList.add(new RadioStation(R.drawable.maneneradiologo, "MANENE RADIO", "--.--", "KISUMU", linksFromTxt.get(100), 100));
        radioStationsList.add(new RadioStation(R.drawable.congasisfmlogo, "CONG'ASIS FM", "88.9", "NAIROBI", linksFromTxt.get(101), 101));
        radioStationsList.add(new RadioStation(R.drawable.northriftradiologo, "NORTHRIFT RADIO", "104.5", "KAPENGURIA", linksFromTxt.get(102), 102));
        radioStationsList.add(new RadioStation(R.drawable.relaxradiologo, "RELAX RADIO", "103.0", "NAIROBI", linksFromTxt.get(103), 103));
        radioStationsList.add(new RadioStation(R.drawable.smashjamradiologo, "SMASH JAM RADIO", "99.0", "NAKURU", linksFromTxt.get(104), 104));
        radioStationsList.add(new RadioStation(R.drawable.getufmlogo, "GETU RADIO", "87.6", "MERU", linksFromTxt.get(105), 105));
        radioStationsList.add(new RadioStation(R.drawable.kokwofmlogo, "KOKWO FM", "100.1", "KAPENGURIA", linksFromTxt.get(106), 106));
        radioStationsList.add(new RadioStation(R.drawable.mumbofmlogo, "MUMBO FM", "90.2", "BUNGOMA", linksFromTxt.get(107), 107));
        radioStationsList.add(new RadioStation(R.drawable.tandazafmlogo, "TANDAZA FM", "103.7", "BUNGOMA", linksFromTxt.get(108), 108));
        radioStationsList.add(new RadioStation(R.drawable.mixxradio560logo, "560 MIXX RADIO", "560kHz", "NAIROBI", linksFromTxt.get(109), 109));
        radioStationsList.add(new RadioStation(R.drawable.christianradiologo560, "560 CHRISTIAN RADIO", "560kHz", "NAIROBI", linksFromTxt.get(110), 110));
        radioStationsList.add(new RadioStation(R.drawable.powercountrylogo560, "560 POWER COUNTRY", "560kHz", "NAIROBI", linksFromTxt.get(111), 111));
        radioStationsList.add(new RadioStation(R.drawable.muthingifmlogo, "MUTHINGI FM", "--.--", "NAIROBI", linksFromTxt.get(225), 225));
        radioStationsList.add(new RadioStation(R.drawable.centralfmlogo, "CENTRAL FM", "97.1", "NANYUKI", linksFromTxt.get(112), 112));
        radioStationsList.add(new RadioStation(R.drawable.mayiengaradiologo, "MAYIENGA FM", "93.5", "BUNGOMA", linksFromTxt.get(113), 113));
        radioStationsList.add(new RadioStation(R.drawable.kitwekradiologo, "KITWEK RADIO", "92.9", "NAIROBI", linksFromTxt.get(114), 114));
        radioStationsList.add(new RadioStation(R.drawable.mwaturadiologo, "MWATU RADIO", "93.1", "MACHAKOS", linksFromTxt.get(115), 115));
        radioStationsList.add(new RadioStation(R.drawable.ingofmlogo, "INGO FM", "100.5", "NAIROBI", linksFromTxt.get(116), 116));
        radioStationsList.add(new RadioStation(R.drawable.powerfmlogo, "POWER FM", "--.--", "NAIROBI", linksFromTxt.get(117), 117));
        radioStationsList.add(new RadioStation(R.drawable.makinikaradiologo, "MAKINIKA RADIO", "--.--", "NAIROBI", linksFromTxt.get(118), 118));
        radioStationsList.add(new RadioStation(R.drawable.bloomradiologo, "BLOOM RADIO", "--.--", "NAIROBI", linksFromTxt.get(119), 119));
        radioStationsList.add(new RadioStation(R.drawable.rainbowradiologo, "RAINBOW RADIO", "---.--", "NAIROBI", linksFromTxt.get(120), 120));
        radioStationsList.add(new RadioStation(R.drawable.togotanefmlogo, "TOGOTANE FM", "88.3", "NAIROBI", linksFromTxt.get(121), 121));
        radioStationsList.add(new RadioStation(R.drawable.eretofmlogo, "ERETO FM", "--.--", "NYERI", linksFromTxt.get(122), 122));
        radioStationsList.add(new RadioStation(R.drawable.midzifmlogo, "MIDZI FM", "100.5", "MALINDI", linksFromTxt.get(123), 123));
        radioStationsList.add(new RadioStation(R.drawable.radio44logo, "RADIO 44", "91.6", "NAIROBI", linksFromTxt.get(124), 124));
        radioStationsList.add(new RadioStation(R.drawable.sayakiradiologo, "SAYAKI RADIO", "--.--", "NYERI", linksFromTxt.get(125), 125));
        radioStationsList.add(new RadioStation(R.drawable.radiosafarilogo, "RADIO SAFARI", "87.9", "KITALE", linksFromTxt.get(126), 126));

        radioStationsList.add(new RadioStation(R.drawable.berurfmlogo, "BERUR FM", "96.7", "NAIROBI", linksFromTxt.get(227), 227));
        radioStationsList.add(new RadioStation(R.drawable.radiofahamulogo, "RADIO FAHAMU", "--.--", "NAIROBI", linksFromTxt.get(127), 127));
        // radioStationsList.add(new RadioStation(R.drawable.mecolfmlogo, "MECOL FM", "--.--", "NAIROBI", linksFromTxt.get(128)));
        radioStationsList.add(new RadioStation(R.drawable.radio254logo, "RADIO 254", "--.--", "NAIROBI", linksFromTxt.get(129), 129));
        radioStationsList.add(new RadioStation(R.drawable.varchradiologo, "VARCH RADIO", "--.--", "ELDORET", linksFromTxt.get(130), 130));
        radioStationsList.add(new RadioStation(R.drawable.radiovunalogo, "RADIO VUNA", "102.0", "KISII", linksFromTxt.get(205), 205));
        radioStationsList.add(new RadioStation(R.drawable.tonziradiologo, "TONZI RADIO", "--.--", "NAIROBI", linksFromTxt.get(131), 131));
        radioStationsList.add(new RadioStation(R.drawable.ifmlogo, "IFM PARTY STATION", "--.--", "NAIROBI", linksFromTxt.get(132), 132));
        radioStationsList.add(new RadioStation(R.drawable.elwaicenterfmlogo, "ELWAI CENTER FM", "--.--", "SUSWA", linksFromTxt.get(133), 133));
        radioStationsList.add(new RadioStation(R.drawable.countrypridefmlogo, "COUNTRY PRIDE FM", "--.--", "NAIROBI", linksFromTxt.get(134), 134));
        radioStationsList.add(new RadioStation(R.drawable.musicjunkieslogo, "MUSICJUNKIES FM", "--.--", "NAIROBI", linksFromTxt.get(135), 135));
        radioStationsList.add(new RadioStation(R.drawable.smoothjazz560logo, "560 SMOOTHJAZZ", "--.--", "NAIROBI", linksFromTxt.get(136), 136));
        radioStationsList.add(new RadioStation(R.drawable.lightfmlogo, "LIGHT FM", "--.--", "NAIROBI", linksFromTxt.get(137), 137));
        radioStationsList.add(new RadioStation(R.drawable.icedfmlogo, "ICED RADIO", "--.--", "NAIROBI", linksFromTxt.get(138), 138));
        radioStationsList.add(new RadioStation(R.drawable.geeradiologo, "GEE RADIO", "--.--", "NAIROBI", linksFromTxt.get(139), 139));
        radioStationsList.add(new RadioStation(R.drawable.tulwoobkoonyradiologo, "TULWOOBKOONY RADIO", "--.--", "NAIROBI", linksFromTxt.get(140), 140));
        radioStationsList.add(new RadioStation(R.drawable.hootersfmlogo, "HOOTERS FM", "--.--", "NAIROBI", linksFromTxt.get(141), 141));
        radioStationsList.add(new RadioStation(R.drawable.kufurahiafmlogo, "KAFURAHA FM", "--.--", "NAIROBI", linksFromTxt.get(142), 142));
        radioStationsList.add(new RadioStation(R.drawable.hoodradiologo, "HOOD RADIO", "--.--", "NAIROBI", linksFromTxt.get(143), 143));
        radioStationsList.add(new RadioStation(R.drawable.abundanceradio, "ABUNDANCE RADIO", "--.--", "NAIROBI", linksFromTxt.get(144), 144));
        radioStationsList.add(new RadioStation(R.drawable.aipcalogo, "AIPCA RADIO", "--.--", "NAIROBI", linksFromTxt.get(145), 145));
        radioStationsList.add(new RadioStation(R.drawable.msenangufmlogo, "MSENANGU FM", "99.5", "MOMBASA", linksFromTxt.get(146), 146));
        radioStationsList.add(new RadioStation(R.drawable.fynradiologo, "FYN RADIO", "--.--", "NAIROBI", linksFromTxt.get(147), 147));
        radioStationsList.add(new RadioStation(R.drawable.xaticfmlogo, "XATIC FM", "--.--", "NAIROBI", linksFromTxt.get(148), 148));
        radioStationsList.add(new RadioStation(R.drawable.tusmofmlogo, "TUSMO FM", "--.--", "NAIROBI", linksFromTxt.get(149), 149));
        radioStationsList.add(new RadioStation(R.drawable.radioshahidilogo, "RADIO SHAHIDI", "91.7", "ISIOLO", linksFromTxt.get(150), 150));
        radioStationsList.add(new RadioStation(R.drawable.pemiradiologo, "PEMI RADIO", "96.1", "NAIROBI", linksFromTxt.get(151), 151));
        radioStationsList.add(new RadioStation(R.drawable.freshfmlogo, "FRESH FM", "--.--", "NAIROBI", linksFromTxt.get(152), 152));
        radioStationsList.add(new RadioStation(R.drawable.hypemagnetradiologo, "HYPEMAGNET RADIO", "--.--", "NAIROBI", linksFromTxt.get(153), 153));
        radioStationsList.add(new RadioStation(R.drawable.mindimoradiologo, "MIDNIMO RADIO", "--.--", "NAIROBI", linksFromTxt.get(154), 154));
        radioStationsList.add(new RadioStation(R.drawable.preachgospelradiologo, "PREACHGOSPEL", "--.--", "KISUMU", linksFromTxt.get(155), 155));
        radioStationsList.add(new RadioStation(R.drawable.radiomikayilogo, "RADIO MIKAYI", "88.8", "HOMABAY", linksFromTxt.get(156), 156));
        radioStationsList.add(new RadioStation(R.drawable.konyonfmlogo, "KONYON FM", "--.--", "KERICHO", linksFromTxt.get(157), 157));
        radioStationsList.add(new RadioStation(R.drawable.pgradiologo, "PG RADIO", "--.--", "KISUMU", linksFromTxt.get(158), 158));
        radioStationsList.add(new RadioStation(R.drawable.aluochrisradiologo, "ALUOCHRIS RADIO", "--.--", "KISUMU", linksFromTxt.get(159), 159));
        radioStationsList.add(new RadioStation(R.drawable.doitordoitfmlogo, "DOITORDOIT", "--.--", "MOMBASA", linksFromTxt.get(160), 160));
        radioStationsList.add(new RadioStation(R.drawable.doctorsexplainlogo, "DOCTORS EXPLAIN", "--.--", "NAIROBI", linksFromTxt.get(161), 161));
        radioStationsList.add(new RadioStation(R.drawable.edenmediaradiologo, "EDEN MEDIA", "--.--", "NAIROBI", linksFromTxt.get(162), 162));
        radioStationsList.add(new RadioStation(R.drawable.xpressradiologo, "XPRESS RADIO", "102.9", "NAIROBI", linksFromTxt.get(163), 163));
        radioStationsList.add(new RadioStation(R.drawable.rasstyleradiologo, "RASSTYLE RADIO", "--.--", "NAIROBI", linksFromTxt.get(164), 164));
        radioStationsList.add(new RadioStation(R.drawable.optimumradiologo, "OPTIMUM RADIO", "--.--", "NAIROBI", linksFromTxt.get(165), 165));
        radioStationsList.add(new RadioStation(R.drawable.radiobarazalogo, "RADIO BARAZA", "--.--", "NAIROBI", linksFromTxt.get(166), 166));
        radioStationsList.add(new RadioStation(R.drawable.radiopunchline, "RADIO PUNCHLINE", "--.--", "NAIROBI", linksFromTxt.get(167), 167));
        radioStationsList.add(new RadioStation(R.drawable.gituambafmlogo, "GITUAMBA FM", "98.2MHz", "NAIROBI", linksFromTxt.get(168), 168));
        radioStationsList.add(new RadioStation(R.drawable.daradiologo, "DA RADIO", "--.--", "NAIROBI", linksFromTxt.get(169), 169));
        radioStationsList.add(new RadioStation(R.drawable.uncutradiologo, "UNCUT RADIO", "--.--", "NAIROBI", linksFromTxt.get(170), 170));
        radioStationsList.add(new RadioStation(R.drawable.gracefmlogo, "GRACE FM", "--.--", "NAIROBI", linksFromTxt.get(171), 171));
        radioStationsList.add(new RadioStation(R.drawable.radiochichilogo, "RADIO CHICHI", "100.7", "BARINGO", linksFromTxt.get(202), 202));
        radioStationsList.add(new RadioStation(R.drawable.theophilusfmlogo, "THEOPHILUS FM", "--.--", "NAIROBI", linksFromTxt.get(221), 221));
        radioStationsList.add(new RadioStation(R.drawable.ebruradiologo, "EBRU RADIO", "89.7", "MANDERA", linksFromTxt.get(222), 222));
        radioStationsList.add(new RadioStation(R.drawable.vybesradiologo, "VYBES RADIO", "104.5", "NAIROBI", linksFromTxt.get(172), 172));
        radioStationsList.add(new RadioStation(R.drawable.starfmlogo, "STAR FM", "105.9", "NAIROBI", linksFromTxt.get(173), 173));
        radioStationsList.add(new RadioStation(R.drawable.mwangazawanenofmlogo, "MWANGAZA WA NENO FM", "--.--", "NAIROBI", linksFromTxt.get(174), 174));
        radioStationsList.add(new RadioStation(R.drawable.thequestradiologo, "THEQUEST RADIO", "--.--", "NAIROBI", linksFromTxt.get(175), 175));
        radioStationsList.add(new RadioStation(R.drawable.radioasuronlogo, "RADIO ASURON", "--.--", "NAIROBI", linksFromTxt.get(176), 176));
        radioStationsList.add(new RadioStation(R.drawable.ruimbofmlogo, "RUIMBO FM", "--.--", "NAIROBI", linksFromTxt.get(177), 177));
        radioStationsList.add(new RadioStation(R.drawable.safinaradiologo, "SAFINA RADIO", "--.--", "NAIROBI", linksFromTxt.get(178), 178));
        radioStationsList.add(new RadioStation(R.drawable.sayarefmlogo, "SAYARE FM", "--.--", "NAIROBI", linksFromTxt.get(179), 179));
        radioStationsList.add(new RadioStation(R.drawable.prasieradiologo, "PRAISE RADIO", "--.--", "NAIROBI", linksFromTxt.get(180), 180));
        radioStationsList.add(new RadioStation(R.drawable.tognofm, "TOGNO FM", "--.--", "NAIROBI", linksFromTxt.get(181), 181));
        radioStationsList.add(new RadioStation(R.drawable.moronigospellogo, "MORONI GOSPEL", "--.--", "NAIROBI", linksFromTxt.get(182), 182));
        radioStationsList.add(new RadioStation(R.drawable.mwanaspotifmlogo, "MWANASPORTI FM", "--.--", "NAIROBI", linksFromTxt.get(183), 183));
        radioStationsList.add(new RadioStation(R.drawable.touchradiologo, "TOUCH RADIO", "--.--", "NAIROBI", linksFromTxt.get(184), 184));
        radioStationsList.add(new RadioStation(R.drawable.uigithaniofmlogo, "UIGITHANIO FM", "--.--", "NAIROBI", linksFromTxt.get(185), 185));
        radioStationsList.add(new RadioStation(R.drawable.radioamanilogo, "RADIO AMANI", "--.--", "NAIROBI", linksFromTxt.get(186), 186));
        radioStationsList.add(new RadioStation(R.drawable.ksmradiologo, "KSM RADIO", "--.--", "NAIROBI", linksFromTxt.get(187), 187));
        radioStationsList.add(new RadioStation(R.drawable.dapstreamradiologo, "DAPSTREAM RADIO", "--.--", "NAIROBI", linksFromTxt.get(188), 188));
        radioStationsList.add(new RadioStation(R.drawable.engelosradiologo, "ENGELOS RADIO", "--.--", "NAIROBI", linksFromTxt.get(189), 189));
        radioStationsList.add(new RadioStation(R.drawable.semafmlogo, "SEMA FM", "98.3", "NAIROBI", linksFromTxt.get(190), 190));
        radioStationsList.add(new RadioStation(R.drawable.kochfmlogo, "KOCH FM", "99.9", "NAIROBI", linksFromTxt.get(191), 191));
        radioStationsList.add(new RadioStation(R.drawable.tsfmlogo, "TS FM", "--.--", "NAIROBI", linksFromTxt.get(192), 192));
        radioStationsList.add(new RadioStation(R.drawable.nworksradiologo, "NWORKS RADIO", "--.--", "NAIROBI", linksFromTxt.get(193), 193));
        radioStationsList.add(new RadioStation(R.drawable.serianfmlogo, "SERIAN FM", "--.--", "NAIROBI", linksFromTxt.get(194), 194));
        radioStationsList.add(new RadioStation(R.drawable.radiomlimalogo, "RADIO MLIMA", "--.--", "NAIROBI", linksFromTxt.get(195), 195));
        radioStationsList.add(new RadioStation(R.drawable.ggvfmlogo, "GGV FM", "--.--", "NAIROBI", linksFromTxt.get(196), 196));
        radioStationsList.add(new RadioStation(R.drawable.popoteradiologo, "POPOTE RADIO", "--.--", "NAIROBI", linksFromTxt.get(197), 197));
        radioStationsList.add(new RadioStation(R.drawable.radiotumainilogo, "RADIO TUMAINI", "93.0", "NAIROBI", linksFromTxt.get(198), 198));
        radioStationsList.add(new RadioStation(R.drawable.badidearadiologo, "BAD IDEA RADIO", "--.--", "NAIROBI", linksFromTxt.get(199), 199));
        radioStationsList.add(new RadioStation(R.drawable.diplomatradiologo, "DIPLOMAT RADIO", "--.--", "NAIROBI", linksFromTxt.get(200), 200));
        radioStationsList.add(new RadioStation(R.drawable.habeshingamusiclogo, "HABESHINGA MUSIC", "--.--", "NAIROBI", linksFromTxt.get(201), 201));


        return radioStationsList;
    }
}