package com.smoothradio.radio.feature.radio_list.util

import com.smoothradio.radio.R
import com.smoothradio.radio.core.model.RadioStation

class RadioStationsHelper {
    companion object {
        fun createRadioStations(linksFromTxt: List<String>, localStations: List<RadioStation>?): List<RadioStation> {
            val radioStationsList = mutableListOf<RadioStation>().apply {
                add(RadioStation(0, R.drawable.hopefm, "HOPE FM", "93.3", "NAIROBI", linksFromTxt[0], false, false))
                add(RadioStation(1, R.drawable.soundcityradiologo, "SOUNDCITY RADIO", "88.5", "NAIROBI", linksFromTxt[1], false, false))
                add(RadioStation(2, R.drawable.kissfm, "KISS FM", "100.3", "NAIROBI", linksFromTxt[2], false, false))
                add(RadioStation(228, R.drawable.radio47logo, "RADIO 47", "103.0", "NAIROBI", linksFromTxt[228], false, false))
                add(RadioStation(3, R.drawable.nrg0, "NRG RADIO", "97.1", "NAIROBI", linksFromTxt[3], false, false))
                add(RadioStation(203, R.drawable.radiocitizenlogo, "RADIO CITIZEN", "106.7", "NAIROBI", linksFromTxt[203], false, false))
                add(RadioStation(4, R.drawable.inooro, "INOORO FM", "98.9", "NAIROBI", linksFromTxt[4], false, false))
                add(RadioStation(5, R.drawable.nrgchoiceradiologo, "CHOICE RADIO", "87.7", "NAIROBI", linksFromTxt[5], false, false))
                add(RadioStation(6, R.drawable.hot96logo, "HOT 96", "96.0", "NAIROBI", linksFromTxt[6], false, false))
                add(RadioStation(7, R.drawable.homeboys, "HOMEBOYS RADIO", "103.5", "NAIROBI", linksFromTxt[7], false, false))
                add(RadioStation(8, R.drawable.classic105_logo, "CLASSIC 105", "105.2", "NAIROBI", linksFromTxt[8], false, false))
                add(RadioStation(9, R.drawable.radiojambologo, "RADIO JAMBO", "97.5", "NAIROBI", linksFromTxt[9], false, false))
                add(RadioStation(26, R.drawable.rogueradiologo, "ROGUE RADIO", "--.--", "NAIROBI", linksFromTxt[26], false, false))
                add(RadioStation(30, R.drawable.tracefmlogo, "TRACE FM", "95.3", "NAIROBI", linksFromTxt[30], false, false))
                add(RadioStation(10, R.drawable.corofmlogo, "CORO FM", "99.5", "NAIROBI", linksFromTxt[10], false, false))
                add(RadioStation(11, R.drawable.kameme, "KAMEME FM", "101.1", "NAIROBI", linksFromTxt[11], false, false))
                add(RadioStation(12, R.drawable.ghettoradiologo, "GHETTO RADIO", "89.5", "NAIROBI", linksFromTxt[12], false, false))
                add(RadioStation(13, R.drawable.radiomaishalogo, "RADIO MAISHA", "102.7", "NAIROBI", linksFromTxt[13], false, false))
                add(RadioStation(14, R.drawable.easyfmlogo, "EASY FM", "96.3", "NAIROBI", linksFromTxt[14], false, false))
                add(RadioStation(15, R.drawable.ramogilogo, "RAMOGI FM", "107.1", "NAIROBI", linksFromTxt[15], false, false))
                add(RadioStation(16, R.drawable.egesalogo, "EGESA FM", "98.6", "NAIROBI", linksFromTxt[16], false, false))
                add(RadioStation(17, R.drawable.mulembelogo, "MULEMBE FM", "97.9", "NAIROBI", linksFromTxt[17], false, false))
                add(RadioStation(18, R.drawable.musyilogo, "MUSYI FM", "102.2", "NAIROBI", linksFromTxt[18], false, false))
                add(RadioStation(19, R.drawable.chamgeilogo, "CHAMGEI FM", "95.0", "NAIROBI", linksFromTxt[19], false, false))
                add(RadioStation(25, R.drawable.kubambaradiologo, "KUBAMBA RADIO", "--.--", "NAIROBI", linksFromTxt[25], false, false))
                add(RadioStation(27, R.drawable.truthfmlogo, "TRUTH FM", "90.7", "NAIROBI", linksFromTxt[27], false, false))
                add(RadioStation(28, R.drawable.familyradiologo, "FAMILY RADIO", "103.9", "NAIROBI", linksFromTxt[28], false, false))
                add(RadioStation(29, R.drawable.jesusislordradiologo, "JESUSISLORD RADIO", "105.3", "NAKURU", linksFromTxt[29], false, false))
                add(RadioStation(31, R.drawable.xfmlogo, "SMOOTH FM", "105.5", "NAIROBI", linksFromTxt[31], false, false))
                add(RadioStation(32, R.drawable.kigoocofmlogo, "KIGOOCO FM", "98.6", "NAIROBI", linksFromTxt[32], false, false))
                add(RadioStation(38, R.drawable.kikuyudiasporaradiologo, "KENYA DIASPORA RADIO", "--.--", "ALABAMA", linksFromTxt[38], false, false))
                add(RadioStation(33, R.drawable.mbciradiologo, "MBCI RADIO", "89.5", "NAKURU", linksFromTxt[33], false, false))
                add(RadioStation(224, R.drawable.gfnradiologo, "GFN FM", "90.1", "TURKANA", linksFromTxt[224], false, false))
                add(RadioStation(44, R.drawable.nationfmlogo, "NATION FM", "96.3", "NAIROBI", linksFromTxt[44], false, false))
                add(RadioStation(54, R.drawable.capitalfmlogo, "CAPITAL FM", "98.4", "NAIROBI", linksFromTxt[54], false, false))
                add(RadioStation(41, R.drawable.gukenafmlogo, "GUKENA FM", "92.8", "NAIROBI", linksFromTxt[41], false, false))
                add(RadioStation(20, R.drawable.muugalogo, "MUUGA FM", "94.2", "NAIROBI", linksFromTxt[20], false, false))
                add(RadioStation(21, R.drawable.sulwelogo, "SULWE FM", "89.6", "NAIROBI", linksFromTxt[21], false, false))
                add(RadioStation(22, R.drawable.wimwarologo, "WIMWARO FM", "93.0", "NAIROBI", linksFromTxt[22], false, false))
                add(RadioStation(23, R.drawable.baharilogo, "BAHARI FM", "90.4", "MOMBASA", linksFromTxt[23], false, false))
                add(RadioStation(24, R.drawable.vuukalogo, "VUUKA FM", "95.4", "NAIROBI", linksFromTxt[24], false, false))
                add(RadioStation(92, R.drawable.lubaofmlogo, "LUBAO FM", "102.2", "KAKAMEGA", linksFromTxt[92], false, false))
                add(RadioStation(34, R.drawable.iqrafmlogo, "IQRA FM", "95.0", "NAIROBI", linksFromTxt[34], false, false))
                add(RadioStation(35, R.drawable.pwanifmlogo, "PWANI FM", "103.1", "MOMBASA", linksFromTxt[35], false, false))
                add(RadioStation(36, R.drawable.sautiyapwanifmlogo, "SAUTIYAPWANI FM", "94.2", "MOMBASA", linksFromTxt[36], false, false))
                add(RadioStation(37, R.drawable.kbcradiotaifalogo, "KBC RADIO TAIFA", "92.9", "NAIROBI", linksFromTxt[37], false, false))
                add(RadioStation(39, R.drawable.taachfmlogo, "TAACH FM", "95.1", "ELDORET", linksFromTxt[39], false, false))
                add(RadioStation(40, R.drawable.eastfmlogo, "EAST FM", "106.3", "NAIROBI", linksFromTxt[40], false, false))
                add(RadioStation(42, R.drawable.kassfmlogo, "KASS FM", "89.1", "NAIROBI", linksFromTxt[42], false, false))
                add(RadioStation(43, R.drawable.soundasialogo, "SOUNDASIA RADIO", "88.0", "NAIROBI", linksFromTxt[43], false, false))
                add(RadioStation(45, R.drawable.wauminilogo, "RADIO WAUMINI", "88.3", "NAIROBI", linksFromTxt[45], false, false))
                add(RadioStation(46, R.drawable.bibiliahusemalogo, "BIBILIA HUSEMA FM", "96.7", "NAIROBI", linksFromTxt[46], false, false))
                add(RadioStation(47, R.drawable.heroradiologo, "HERO RADIO", "99.0", "NAKURU", linksFromTxt[47], false, false))
                add(RadioStation(48, R.drawable.milelefmlogo, "MILELE FM", "104.8", "NAIROBI", linksFromTxt[48], false, false))
                add(RadioStation(207, R.drawable.getembefmlogo, "GETEMBE FM", "102.7", "KISII", linksFromTxt[207], false, false))
                add(RadioStation(208, R.drawable.inkafmlogo, "INKA FM", "93.7", "KISII", linksFromTxt[208], false, false))
                add(RadioStation(49, R.drawable.radiokayalogo, "RADIO KAYA", "93.1", "NAIROBI", linksFromTxt[49], false, false))
                add(RadioStation(50, R.drawable.spicefmlogo, "SPICE FM", "94.4", "NAIROBI", linksFromTxt[50], false, false))
                add(RadioStation(51, R.drawable.barakafmlogo, "BARAKA FM", "95.5", "MOMBASA", linksFromTxt[51], false, false))
                add(RadioStation(52, R.drawable.radioinjililogo, "RADIO INJILI", "103.7", "KERICHO", linksFromTxt[52], false, false))
                add(RadioStation(53, R.drawable.athianilogo, "ATHIANI FM", "99.2", "NAIROBI", linksFromTxt[53], false, false))
                add(RadioStation(55, R.drawable.beatlocklogo, "BEATLOCK RADIO", "--.--", "NAIROBI", linksFromTxt[55], false, false))
                add(RadioStation(56, R.drawable.pearlxtralogo, "PEARL XTRA FM", "--.--", "NAIROBI", linksFromTxt[56], false, false))
                add(RadioStation(57, R.drawable.theupperroomlogo, "THE UPPERROOM FM", "--.--", "NAIROBI", linksFromTxt[57], false, false))
                add(RadioStation(58, R.drawable.lulufmlogo, "LULU FM", "91.0", "MOMBASA", linksFromTxt[58], false, false))
                add(RadioStation(59, R.drawable.pearlradiologo, "PEARL RADIO", "96.9", "NAIROBI", linksFromTxt[59], false, false))
                add(RadioStation(60, R.drawable.imaniradiologo, "IMANI RADIO", "88.8", "KITALE", linksFromTxt[60], false, false))
                add(RadioStation(61, R.drawable.lionafriqradiologo, "LIONAFRIQ RADIO", "--.--", "NAIROBI", linksFromTxt[61], false, false))
                add(RadioStation(211, R.drawable.nrg_hiphop_logo, "NRG HIPHOP", "--.--", "NAIROBI", linksFromTxt[211], false, false))
                add(RadioStation(212, R.drawable.nrg_dancehall_logo, "NRG DANCEHALL", "--.--", "NAIROBI", linksFromTxt[212], false, false))
                add(RadioStation(213, R.drawable.nrg_gospel_logo, "NRG GOSPEL", "--.--", "NAIROBI", linksFromTxt[213], false, false))
                add(RadioStation(214, R.drawable.nrg_afrobeats_logo, "NRG AFROBEATS", "--.--", "NAIROBI", linksFromTxt[214], false, false))
                add(RadioStation(215, R.drawable.nrg_mixology_logo, "NRG MIXOLOGY", "--.--", "NAIROBI", linksFromTxt[215], false, false))
                add(RadioStation(216, R.drawable.nrg_rnb_logo, "NRG RNB", "--.--", "NAIROBI", linksFromTxt[216], false, false))
                add(RadioStation(217, R.drawable.nrg_jazz_logo, "NRG JAZZ", "--.--", "NAIROBI", linksFromTxt[217], false, false))
                add(RadioStation(204, R.drawable.longaradiologo, "LONGA RADIO", "--.--", "NAIROBI", linksFromTxt[204], false, false))
                add(RadioStation(226, R.drawable.kayufmlogo, "KAYU FM", "91.0", "NAIROBI", linksFromTxt[226], false, false))
                add(RadioStation(62, R.drawable.flamingoradiologo, "FLAMINGO FM", "93.7", "NAKURU", linksFromTxt[62], false, false))
                add(RadioStation(63, R.drawable.pilipilifmlogo, "PILIPILI FM", "99.5", "NAIROBI", linksFromTxt[63], false, false))
                add(RadioStation(209, R.drawable.kerioradiologo, "KERIO RADIO", "87.6", "BARINGO", linksFromTxt[209], false, false))
                add(RadioStation(210, R.drawable.tausifmlogo, "TAUSI FM", "--.--", "NAIROBI", linksFromTxt[210], false, false))
                add(RadioStation(229, R.drawable.hillsidefmlogo, "HILLSIDE FM", "--.--", "NAIROBI", linksFromTxt[229], false, false))
                add(RadioStation(230, R.drawable.pefaradoilogo, "PEFA RADIO", "--.--", "NAIROBI", linksFromTxt[230], false, false))
                add(RadioStation(64, R.drawable.mayianfmlogo, "MAYIAN FM", "100.7", "NAROK", linksFromTxt[64], false, false))
                add(RadioStation(65, R.drawable.merufmlogo, "MERU FM", "100.3", "MERU", linksFromTxt[65], false, false))
                add(RadioStation(66, R.drawable.emoofmlogo, "EMOO FM", "104.2", "NAIROBI", linksFromTxt[66], false, false))
                add(RadioStation(223, R.drawable.mutongoifmlogo, "MUTONGOI FM", "103.3", "KITUI", linksFromTxt[223], false, false))
                add(RadioStation(218, R.drawable.mwagofmlogo, "MWANGO FM", "97.5", "NAIROBI", linksFromTxt[218], false, false))
                add(RadioStation(219, R.drawable.nosimfmlogo, "NOSIM FM", "90.5", "NAIROBI", linksFromTxt[219], false, false))
                add(RadioStation(220, R.drawable.osiepefmlogo, "OSIEPE FM", "96.8", "SIAYA", linksFromTxt[220], false, false))
                add(RadioStation(67, R.drawable.radiosalaamlogo, "RADIO SALAAM", "90.7", "MOMBASA", linksFromTxt[67], false, false))
                add(RadioStation(68, R.drawable.radiorahmalogo, "RADIO RAHMA", "91.5", "MOMBASA", linksFromTxt[68], false, false))
                add(RadioStation(69, R.drawable.asylumradiologo, "ASYLUM RADIO", "--.--", "NAIROBI", linksFromTxt[69], false, false))
                add(RadioStation(70, R.drawable.kbcenglishservicelogo, "KBC ENGLISH SERVICE", "95.6", "NAIROBI", linksFromTxt[70], false, false))
                add(RadioStation(71, R.drawable.mbaitufmlogo, "MBAITU FM", "92.5", "MACHAKOS", linksFromTxt[71], false, false))
                add(RadioStation(72, R.drawable.radio_maria, "RADIO MARIA", "90.0", "NAIROBI", linksFromTxt[72], false, false))
                add(RadioStation(73, R.drawable.upendoradiologo, "UPENDO RADIO", "89.4", "ELDORET", linksFromTxt[73], false, false))
                add(RadioStation(74, R.drawable.hiphopginlogo, "HIPHOPGIN", "--.--", "NAIROBI", linksFromTxt[74], false, false))
                add(RadioStation(75, R.drawable.hiphopdailylogo, "HIPHOP DAILY", "97.5", "NAIROBI", linksFromTxt[75], false, false))
                add(RadioStation(79, R.drawable.rfmlogo, "R FM", "99.9", "LIMURU", linksFromTxt[79], false, false))
                add(RadioStation(76, R.drawable.tulizafmlogo, "TULIZA FM", "94.2", "MERU", linksFromTxt[76], false, false))
                add(RadioStation(77, R.drawable.kihootofmlogo, "KIHOOTO FM", "91.2", "NAIROBI", linksFromTxt[77], false, false))
                add(RadioStation(78, R.drawable.kisiifmlogo, "KISII FM", "94.1", "NAIROBI", linksFromTxt[78], false, false))
                add(RadioStation(80, R.drawable.seitofmlogo, "SEITO FM", "100.3", "NAIROBI", linksFromTxt[80], false, false))
                add(RadioStation(81, R.drawable.sifafmlogo, "SIFA FM", "101.2", "MARSABIT", linksFromTxt[81], false, false))
                add(RadioStation(82, R.drawable.countyfmlogo, "COUNTY FM", "90.3", "KITUI", linksFromTxt[82], false, false))
                add(RadioStation(83, R.drawable.sidaifmlogo, "SIDAI FM", "103.5", "NAROK", linksFromTxt[83], false, false))
                add(RadioStation(84, R.drawable.radioneemalogo, "RADIO NEEMA", "--.--", "NAIROBI", linksFromTxt[84], false, false))
                add(RadioStation(85, R.drawable.radiosimbalogo, "RADIO SIMBA", "93.1", "BUNGOMA", linksFromTxt[85], false, false))
                add(RadioStation(86, R.drawable.westfmlogo, "WEST FM", "94.9", "NAIROBI", linksFromTxt[86], false, false))
                add(RadioStation(87, R.drawable.iftinfmlogo, "IFTIIN FM", "101.9", "NAIROBI", linksFromTxt[87], false, false))
                add(RadioStation(88, R.drawable.mintofmlogo, "MINTO FM", "101.7", "NAIROBI", linksFromTxt[88], false, false))
                add(RadioStation(89, R.drawable.bikapkoretradiologo, "BIKAPKORET RADIO", "98.2", "ELDORET", linksFromTxt[89], false, false))
                add(RadioStation(90, R.drawable.muratafmlogo, "MURATA FM", "98.2", "ELDORET", linksFromTxt[90], false, false))
                add(RadioStation(91, R.drawable.campusradiologo, "CAMPUS RADIO", "--.--", "NAIROBI", linksFromTxt[91], false, false))
                add(RadioStation(93, R.drawable.utheriradiologo, "UTHERI RADIO", "106.2", "NAIROBI", linksFromTxt[93], false, false))
                add(RadioStation(94, R.drawable.mugambowamugikuyulogo, "MUGAMBO WA MUGIKUYU", "--.--", "NAIROBI", linksFromTxt[94], false, false))
                add(RadioStation(95, R.drawable.mwakifmlogo, "MWAKI FM", "--.--", "NAIROBI", linksFromTxt[95], false, false))
                add(RadioStation(96, R.drawable.shilohradiologo, "SHILOH RADIO", "--.--", "NAIROBI", linksFromTxt[96], false, false))
                add(RadioStation(97, R.drawable.cambrigeradiologo, "CAMBRIDGE RADIO", "--.--", "NAIROBI", linksFromTxt[97], false, false))
                add(RadioStation(98, R.drawable.angeladventistlogo, "ADVENTIST ANGELS", "90.0", "KISII", linksFromTxt[98], false, false))
                add(RadioStation(99, R.drawable.utuuroradiologo, "UTUURO RADIO", "--.--", "NAIROBI", linksFromTxt[99], false, false))
                add(RadioStation(100, R.drawable.maneneradiologo, "MANENE RADIO", "--.--", "KISUMU", linksFromTxt[100], false, false))
                add(RadioStation(101, R.drawable.congasisfmlogo, "CONG'ASIS FM", "88.9", "NAIROBI", linksFromTxt[101], false, false))
                add(RadioStation(102, R.drawable.northriftradiologo, "NORTHRIFT RADIO", "104.5", "KAPENGURIA", linksFromTxt[102], false, false))
                add(RadioStation(103, R.drawable.relaxradiologo, "RELAX RADIO", "103.0", "NAIROBI", linksFromTxt[103], false, false))
                add(RadioStation(104, R.drawable.smashjamradiologo, "SMASH JAM RADIO", "99.0", "NAKURU", linksFromTxt[104], false, false))
                add(RadioStation(105, R.drawable.getufmlogo, "GETU RADIO", "87.6", "MERU", linksFromTxt[105], false, false))
                add(RadioStation(106, R.drawable.kokwofmlogo, "KOKWO FM", "100.1", "KAPENGURIA", linksFromTxt[106], false, false))
                add(RadioStation(107, R.drawable.mumbofmlogo, "MUMBO FM", "90.2", "BUNGOMA", linksFromTxt[107], false, false))
                add(RadioStation(108, R.drawable.tandazafmlogo, "TANDAZA FM", "103.7", "BUNGOMA", linksFromTxt[108], false, false))
                add(RadioStation(109, R.drawable.mixxradio560logo, "560 MIXX RADIO", "560kHz", "NAIROBI", linksFromTxt[109], false, false))
                add(RadioStation(110, R.drawable.christianradiologo560, "560 CHRISTIAN RADIO", "560kHz", "NAIROBI", linksFromTxt[110], false, false))
                add(RadioStation(111, R.drawable.powercountrylogo560, "560 POWER COUNTRY", "560kHz", "NAIROBI", linksFromTxt[111], false, false))
                add(RadioStation(225, R.drawable.muthingifmlogo, "MUTHINGI FM", "--.--", "NAIROBI", linksFromTxt[225], false, false))
                add(RadioStation(112, R.drawable.centralfmlogo, "CENTRAL FM", "97.1", "NANYUKI", linksFromTxt[112], false, false))
                add(RadioStation(113, R.drawable.mayiengaradiologo, "MAYIENGA FM", "93.5", "BUNGOMA", linksFromTxt[113], false, false))
                add(RadioStation(114, R.drawable.kitwekradiologo, "KITWEK RADIO", "92.9", "NAIROBI", linksFromTxt[114], false, false))
                add(RadioStation(115, R.drawable.mwaturadiologo, "MWATU RADIO", "93.1", "MACHAKOS", linksFromTxt[115], false, false))
                add(RadioStation(116, R.drawable.ingofmlogo, "INGO FM", "100.5", "NAIROBI", linksFromTxt[116], false, false))
                add(RadioStation(117, R.drawable.powerfmlogo, "POWER FM", "--.--", "NAIROBI", linksFromTxt[117], false, false))
                add(RadioStation(118, R.drawable.makinikaradiologo, "MAKINIKA RADIO", "--.--", "NAIROBI", linksFromTxt[118], false, false))
                add(RadioStation(119, R.drawable.bloomradiologo, "BLOOM RADIO", "--.--", "NAIROBI", linksFromTxt[119], false, false))
                add(RadioStation(120, R.drawable.rainbowradiologo, "RAINBOW RADIO", "---.--", "NAIROBI", linksFromTxt[120], false, false))
                add(RadioStation(121, R.drawable.togotanefmlogo, "TOGOTANE FM", "88.3", "NAIROBI", linksFromTxt[121], false, false))
                add(RadioStation(122, R.drawable.eretofmlogo, "ERETO FM", "--.--", "NYERI", linksFromTxt[122], false, false))
                add(RadioStation(123, R.drawable.midzifmlogo, "MIDZI FM", "100.5", "MALINDI", linksFromTxt[123], false, false))
                add(RadioStation(124, R.drawable.radio44logo, "RADIO 44", "91.6", "NAIROBI", linksFromTxt[124], false, false))
                add(RadioStation(125, R.drawable.sayakiradiologo, "SAYAKI RADIO", "--.--", "NYERI", linksFromTxt[125], false, false))
                add(RadioStation(126, R.drawable.radiosafarilogo, "RADIO SAFARI", "87.9", "KITALE", linksFromTxt[126], false, false))
                add(RadioStation(227, R.drawable.berurfmlogo, "BERUR FM", "96.7", "NAIROBI", linksFromTxt[227], false, false))
                add(RadioStation(127, R.drawable.radiofahamulogo, "RADIO FAHAMU", "--.--", "NAIROBI", linksFromTxt[127], false, false))
                add(RadioStation(129, R.drawable.radio254logo, "RADIO 254", "--.--", "NAIROBI", linksFromTxt[129], false, false))
                add(RadioStation(130, R.drawable.varchradiologo, "VARCH RADIO", "--.--", "ELDORET", linksFromTxt[130], false, false))
                add(RadioStation(205, R.drawable.radiovunalogo, "RADIO VUNA", "102.0", "KISII", linksFromTxt[205], false, false))
                add(RadioStation(131, R.drawable.tonziradiologo, "TONZI RADIO", "--.--", "NAIROBI", linksFromTxt[131], false, false))
                add(RadioStation(132, R.drawable.ifmlogo, "IFM PARTY STATION", "--.--", "NAIROBI", linksFromTxt[132], false, false))
                add(RadioStation(133, R.drawable.elwaicenterfmlogo, "ELWAI CENTER FM", "--.--", "SUSWA", linksFromTxt[133], false, false))
                add(RadioStation(134, R.drawable.countrypridefmlogo, "COUNTRY PRIDE FM", "--.--", "NAIROBI", linksFromTxt[134], false, false))
                add(RadioStation(135, R.drawable.musicjunkieslogo, "MUSICJUNKIES FM", "--.--", "NAIROBI", linksFromTxt[135], false, false))
                add(RadioStation(136, R.drawable.smoothjazz560logo, "560 SMOOTHJAZZ", "--.--", "NAIROBI", linksFromTxt[136], false, false))
                add(RadioStation(137, R.drawable.lightfmlogo, "LIGHT FM", "--.--", "NAIROBI", linksFromTxt[137], false, false))
                add(RadioStation(138, R.drawable.icedfmlogo, "ICED RADIO", "--.--", "NAIROBI", linksFromTxt[138], false, false))
                add(RadioStation(139, R.drawable.geeradiologo, "GEE RADIO", "--.--", "NAIROBI", linksFromTxt[139], false, false))
                add(RadioStation(140, R.drawable.tulwoobkoonyradiologo, "TULWOOBKOONY RADIO", "--.--", "NAIROBI", linksFromTxt[140], false, false))
                add(RadioStation(141, R.drawable.hootersfmlogo, "HOOTERS FM", "--.--", "NAIROBI", linksFromTxt[141], false, false))
                add(RadioStation(142, R.drawable.kufurahiafmlogo, "KAFURAHA FM", "--.--", "NAIROBI", linksFromTxt[142], false, false))
                add(RadioStation(143, R.drawable.hoodradiologo, "HOOD RADIO", "--.--", "NAIROBI", linksFromTxt[143], false, false))
                add(RadioStation(144, R.drawable.abundanceradio, "ABUNDANCE RADIO", "--.--", "NAIROBI", linksFromTxt[144], false, false))
                add(RadioStation(145, R.drawable.aipcalogo, "AIPCA RADIO", "--.--", "NAIROBI", linksFromTxt[145], false, false))
                add(RadioStation(146, R.drawable.msenangufmlogo, "MSENANGU FM", "99.5", "MOMBASA", linksFromTxt[146], false, false))
                add(RadioStation(147, R.drawable.fynradiologo, "FYN RADIO", "--.--", "NAIROBI", linksFromTxt[147], false, false))
                add(RadioStation(148, R.drawable.xaticfmlogo, "XATIC FM", "--.--", "NAIROBI", linksFromTxt[148], false, false))
                add(RadioStation(149, R.drawable.tusmofmlogo, "TUSMO FM", "--.--", "NAIROBI", linksFromTxt[149], false, false))
                add(RadioStation(150, R.drawable.radioshahidilogo, "RADIO SHAHIDI", "91.7", "ISIOLO", linksFromTxt[150], false, false))
                add(RadioStation(151, R.drawable.pemiradiologo, "PEMI RADIO", "96.1", "NAIROBI", linksFromTxt[151], false, false))
                add(RadioStation(152, R.drawable.freshfmlogo, "FRESH FM", "--.--", "NAIROBI", linksFromTxt[152], false, false))
                add(RadioStation(153, R.drawable.hypemagnetradiologo, "HYPEMAGNET RADIO", "--.--", "NAIROBI", linksFromTxt[153], false, false))
                add(RadioStation(154, R.drawable.mindimoradiologo, "MIDNIMO RADIO", "--.--", "NAIROBI", linksFromTxt[154], false, false))
                add(RadioStation(155, R.drawable.preachgospelradiologo, "PREACHGOSPEL", "--.--", "KISUMU", linksFromTxt[155], false, false))
                add(RadioStation(156, R.drawable.radiomikayilogo, "RADIO MIKAYI", "88.8", "HOMABAY", linksFromTxt[156], false, false))
                add(RadioStation(157, R.drawable.konyonfmlogo, "KONYON FM", "--.--", "KERICHO", linksFromTxt[157], false, false))
                add(RadioStation(158, R.drawable.pgradiologo, "PG RADIO", "--.--", "KISUMU", linksFromTxt[158], false, false))
                add(RadioStation(159, R.drawable.aluochrisradiologo, "ALUOCHRIS RADIO", "--.--", "KISUMU", linksFromTxt[159], false, false))
                add(RadioStation(160, R.drawable.doitordoitfmlogo, "DOITORDOIT", "--.--", "MOMBASA", linksFromTxt[160], false, false))
                add(RadioStation(161, R.drawable.doctorsexplainlogo, "DOCTORS EXPLAIN", "--.--", "NAIROBI", linksFromTxt[161], false, false))
                add(RadioStation(162, R.drawable.edenmediaradiologo, "EDEN MEDIA", "--.--", "NAIROBI", linksFromTxt[162], false, false))
                add(RadioStation(163, R.drawable.xpressradiologo, "XPRESS RADIO", "102.9", "NAIROBI", linksFromTxt[163], false, false))
                add(RadioStation(164, R.drawable.rasstyleradiologo, "RASSTYLE RADIO", "--.--", "NAIROBI", linksFromTxt[164], false, false))
                add(RadioStation(165, R.drawable.optimumradiologo, "OPTIMUM RADIO", "--.--", "NAIROBI", linksFromTxt[165], false, false))
                add(RadioStation(166, R.drawable.radiobarazalogo, "RADIO BARAZA", "--.--", "NAIROBI", linksFromTxt[166], false, false))
                add(RadioStation(167, R.drawable.radiopunchline, "RADIO PUNCHLINE", "--.--", "NAIROBI", linksFromTxt[167], false, false))
                add(RadioStation(168, R.drawable.gituambafmlogo, "GITUAMBA FM", "98.2MHz", "NAIROBI", linksFromTxt[168], false, false))
                add(RadioStation(169, R.drawable.daradiologo, "DA RADIO", "--.--", "NAIROBI", linksFromTxt[169], false, false))
                add(RadioStation(170, R.drawable.uncutradiologo, "UNCUT RADIO", "--.--", "NAIROBI", linksFromTxt[170], false, false))
                add(RadioStation(171, R.drawable.gracefmlogo, "GRACE FM", "--.--", "NAIROBI", linksFromTxt[171], false, false))
                add(RadioStation(202, R.drawable.radiochichilogo, "RADIO CHICHI", "100.7", "BARINGO", linksFromTxt[202], false, false))
                add(RadioStation(221, R.drawable.theophilusfmlogo, "THEOPHILUS FM", "--.--", "NAIROBI", linksFromTxt[221], false, false))
                add(RadioStation(222, R.drawable.ebruradiologo, "EBRU RADIO", "89.7", "MANDERA", linksFromTxt[222], false, false))
                add(RadioStation(172, R.drawable.vybesradiologo, "VYBES RADIO", "104.5", "NAIROBI", linksFromTxt[172], false, false))
                add(RadioStation(173, R.drawable.starfmlogo, "STAR FM", "105.9", "NAIROBI", linksFromTxt[173], false, false))
                add(RadioStation(174, R.drawable.mwangazawanenofmlogo, "MWANGAZA WA NENO FM", "--.--", "NAIROBI", linksFromTxt[174], false, false))
                add(RadioStation(175, R.drawable.thequestradiologo, "THEQUEST RADIO", "--.--", "NAIROBI", linksFromTxt[175], false, false))
                add(RadioStation(176, R.drawable.radioasuronlogo, "RADIO ASURON", "--.--", "NAIROBI", linksFromTxt[176], false, false))
                add(RadioStation(177, R.drawable.ruimbofmlogo, "RUIMBO FM", "--.--", "NAIROBI", linksFromTxt[177], false, false))
                add(RadioStation(178, R.drawable.safinaradiologo, "SAFINA RADIO", "--.--", "NAIROBI", linksFromTxt[178], false, false))
                add(RadioStation(179, R.drawable.sayarefmlogo, "SAYARE FM", "--.--", "NAIROBI", linksFromTxt[179], false, false))
                add(RadioStation(180, R.drawable.prasieradiologo, "PRAISE RADIO", "--.--", "NAIROBI", linksFromTxt[180], false, false))
                add(RadioStation(181, R.drawable.tognofm, "TOGNO FM", "--.--", "NAIROBI", linksFromTxt[181], false, false))
                add(RadioStation(182, R.drawable.moronigospellogo, "MORONI GOSPEL", "--.--", "NAIROBI", linksFromTxt[182], false, false))
                add(RadioStation(183, R.drawable.mwanaspotifmlogo, "MWANASPORTI FM", "--.--", "NAIROBI", linksFromTxt[183], false, false))
                add(RadioStation(184, R.drawable.touchradiologo, "TOUCH RADIO", "--.--", "NAIROBI", linksFromTxt[184], false, false))
                add(RadioStation(185, R.drawable.uigithaniofmlogo, "UIGITHANIO FM", "--.--", "NAIROBI", linksFromTxt[185], false, false))
                add(RadioStation(186, R.drawable.radioamanilogo, "RADIO AMANI", "--.--", "NAIROBI", linksFromTxt[186], false, false))
                add(RadioStation(187, R.drawable.ksmradiologo, "KSM RADIO", "--.--", "NAIROBI", linksFromTxt[187], false, false))
                add(RadioStation(188, R.drawable.dapstreamradiologo, "DAPSTREAM RADIO", "--.--", "NAIROBI", linksFromTxt[188], false, false))
                add(RadioStation(189, R.drawable.engelosradiologo, "ENGELOS RADIO", "--.--", "NAIROBI", linksFromTxt[189], false, false))
                add(RadioStation(190, R.drawable.semafmlogo, "SEMA FM", "98.3", "NAIROBI", linksFromTxt[190], false, false))
                add(RadioStation(191, R.drawable.kochfmlogo, "KOCH FM", "99.9", "NAIROBI", linksFromTxt[191], false, false))
                add(RadioStation(192, R.drawable.tsfmlogo, "TS FM", "--.--", "NAIROBI", linksFromTxt[192], false, false))
                add(RadioStation(193, R.drawable.nworksradiologo, "NWORKS RADIO", "--.--", "NAIROBI", linksFromTxt[193], false, false))
                add(RadioStation(194, R.drawable.serianfmlogo, "SERIAN FM", "--.--", "NAIROBI", linksFromTxt[194], false, false))
                add(RadioStation(195, R.drawable.radiomlimalogo, "RADIO MLIMA", "--.--", "NAIROBI", linksFromTxt[195], false, false))
                add(RadioStation(196, R.drawable.ggvfmlogo, "GGV FM", "--.--", "NAIROBI", linksFromTxt[196], false, false))
                add(RadioStation(197, R.drawable.popoteradiologo, "POPOTE RADIO", "--.--", "NAIROBI", linksFromTxt[197], false, false))
                add(RadioStation(198, R.drawable.radiotumainilogo, "RADIO TUMAINI", "93.0", "NAIROBI", linksFromTxt[198], false, false))
                add(RadioStation(199, R.drawable.badidearadiologo, "BAD IDEA RADIO", "--.--", "NAIROBI", linksFromTxt[199], false, false))
                add(RadioStation(200, R.drawable.diplomatradiologo, "DIPLOMAT RADIO", "--.--", "NAIROBI", linksFromTxt[200], false, false))
                add(RadioStation(201, R.drawable.habeshingamusiclogo, "HABESHINGA MUSIC", "--.--", "NAIROBI", linksFromTxt[201], false, false))
            }

            // Merge local favorites and playing states
            localStations?.forEach { local ->
                radioStationsList.find { it.id == local.id }?.apply {
                    if (local.isFavorite) this.isFavorite = true
                    if (local.isPlaying) this.isPlaying = true
                }
            }

            return radioStationsList
        }
    }
}