package com.smoothradio.radio.core.util

import androidx.annotation.DrawableRes
import com.smoothradio.radio.R

object LogoMapper {
    @DrawableRes
    fun getLogoById(id: Int): Int {
        return when (id) {
            0 -> R.drawable.hopefm
            1 -> R.drawable.soundcityradiologo
            2 -> R.drawable.kissfm
            228 -> R.drawable.radio47logo
            3 -> R.drawable.nrg0
            203 -> R.drawable.radiocitizenlogo
            4 -> R.drawable.inooro
            5 -> R.drawable.nrgchoiceradiologo
            6 -> R.drawable.hot96logo
            7 -> R.drawable.homeboys
            8 -> R.drawable.classic105_logo
            9 -> R.drawable.radiojambologo
            26 -> R.drawable.rogueradiologo
            30 -> R.drawable.tracefmlogo
            10 -> R.drawable.corofmlogo
            11 -> R.drawable.kameme
            12 -> R.drawable.ghettoradiologo
            13 -> R.drawable.radiomaishalogo
            14 -> R.drawable.easyfmlogo
            15 -> R.drawable.ramogilogo
            16 -> R.drawable.egesalogo
            17 -> R.drawable.mulembelogo
            18 -> R.drawable.musyilogo
            19 -> R.drawable.chamgeilogo
            25 -> R.drawable.kubambaradiologo
            27 -> R.drawable.truthfmlogo
            28 -> R.drawable.familyradiologo
            29 -> R.drawable.jesusislordradiologo
            31 -> R.drawable.xfmlogo
            32 -> R.drawable.kigoocofmlogo
            38 -> R.drawable.kikuyudiasporaradiologo
            33 -> R.drawable.mbciradiologo
            44 -> R.drawable.nationfmlogo
            54 -> R.drawable.capitalfmlogo
            231 -> R.drawable.kwitufmlogo
            41 -> R.drawable.gukenafmlogo
            20 -> R.drawable.muugalogo
            21 -> R.drawable.sulwelogo
            22 -> R.drawable.wimwarologo
            23 -> R.drawable.baharilogo
            24 -> R.drawable.vuukalogo
            92 -> R.drawable.lubaofmlogo
            34 -> R.drawable.iqrafmlogo
            35 -> R.drawable.pwanifmlogo
            36 -> R.drawable.sautiyapwanifmlogo
            37 -> R.drawable.kbcradiotaifalogo
            39 -> R.drawable.taachfmlogo
            40 -> R.drawable.eastfmlogo
            42 -> R.drawable.kassfmlogo
            43 -> R.drawable.soundasialogo
            45 -> R.drawable.wauminilogo
            46 -> R.drawable.bibiliahusemalogo
            47 -> R.drawable.heroradiologo
            48 -> R.drawable.milelefmlogo
            207 -> R.drawable.getembefmlogo
            208 -> R.drawable.inkafmlogo
            49 -> R.drawable.radiokayalogo
            50 -> R.drawable.spicefmlogo
            51 -> R.drawable.barakafmlogo
            52 -> R.drawable.radioinjililogo
            53 -> R.drawable.athianilogo
            55 -> R.drawable.beatlocklogo
            56 -> R.drawable.pearlxtralogo
            57 -> R.drawable.theupperroomlogo
            58 -> R.drawable.lulufmlogo
            59 -> R.drawable.pearlradiologo
            60 -> R.drawable.imaniradiologo
            61 -> R.drawable.lionafriqradiologo
            211 -> R.drawable.nrg_hiphop_logo
            212 -> R.drawable.nrg_dancehall_logo
            213 -> R.drawable.nrg_gospel_logo
            214 -> R.drawable.nrg_afrobeats_logo
            215 -> R.drawable.nrg_mixology_logo
            216 -> R.drawable.nrg_rnb_logo
            217 -> R.drawable.nrg_jazz_logo
            204 -> R.drawable.longaradiologo
            226 -> R.drawable.kayufmlogo
            62 -> R.drawable.flamingoradiologo
            209 -> R.drawable.kerioradiologo
            210 -> R.drawable.tausifmlogo
            229 -> R.drawable.hillsidefmlogo
            230 -> R.drawable.pefaradoilogo
            64 -> R.drawable.mayianfmlogo
            65 -> R.drawable.merufmlogo
            66 -> R.drawable.emoofmlogo
            223 -> R.drawable.mutongoifmlogo
            218 -> R.drawable.mwagofmlogo
            219 -> R.drawable.nosimfmlogo
            220 -> R.drawable.osiepefmlogo
            67 -> R.drawable.radiosalaamlogo
            68 -> R.drawable.radiorahmalogo
            70 -> R.drawable.kbcenglishservicelogo
            71 -> R.drawable.mbaitufmlogo
            72 -> R.drawable.radio_maria
            73 -> R.drawable.upendoradiologo
            74 -> R.drawable.hiphopginlogo
            75 -> R.drawable.hiphopdailylogo
            79 -> R.drawable.rfmlogo
            76 -> R.drawable.tulizafmlogo
            77 -> R.drawable.kihootofmlogo
            78 -> R.drawable.kisiifmlogo
            80 -> R.drawable.seitofmlogo
            81 -> R.drawable.sifafmlogo
            82 -> R.drawable.countyfmlogo
            83 -> R.drawable.sidaifmlogo
            84 -> R.drawable.radioneemalogo
            85 -> R.drawable.radiosimbalogo
            86 -> R.drawable.westfmlogo
            87 -> R.drawable.iftinfmlogo
            88 -> R.drawable.mintofmlogo
            89 -> R.drawable.bikapkoretradiologo
            90 -> R.drawable.muratafmlogo
            91 -> R.drawable.campusradiologo
            93 -> R.drawable.utheriradiologo
            94 -> R.drawable.mugambowamugikuyulogo
            95 -> R.drawable.mwakifmlogo
            96 -> R.drawable.shilohradiologo
            98 -> R.drawable.angeladventistlogo
            99 -> R.drawable.utuuroradiologo
            100 -> R.drawable.maneneradiologo
            101 -> R.drawable.congasisfmlogo
            102 -> R.drawable.northriftradiologo
            103 -> R.drawable.relaxradiologo
            104 -> R.drawable.smashjamradiologo
            105 -> R.drawable.getufmlogo
            106 -> R.drawable.kokwofmlogo
            107 -> R.drawable.mumbofmlogo
            108 -> R.drawable.tandazafmlogo
            109 -> R.drawable.mixxradio560logo
            110 -> R.drawable.christianradiologo560
            111 -> R.drawable.powercountrylogo560
            225 -> R.drawable.muthingifmlogo
            112 -> R.drawable.centralfmlogo
            113 -> R.drawable.mayiengaradiologo
            114 -> R.drawable.kitwekradiologo
            115 -> R.drawable.mwaturadiologo
            116 -> R.drawable.ingofmlogo
            117 -> R.drawable.powerfmlogo
            118 -> R.drawable.makinikaradiologo
            119 -> R.drawable.bloomradiologo
            120 -> R.drawable.rainbowradiologo
            121 -> R.drawable.togotanefmlogo
            122 -> R.drawable.eretofmlogo
            123 -> R.drawable.midzifmlogo
            124 -> R.drawable.radio44logo
            125 -> R.drawable.sayakiradiologo
            126 -> R.drawable.radiosafarilogo
            227 -> R.drawable.berurfmlogo
            127 -> R.drawable.radiofahamulogo
            129 -> R.drawable.radio254logo
            130 -> R.drawable.varchradiologo
            205 -> R.drawable.radiovunalogo
            131 -> R.drawable.tonziradiologo
            133 -> R.drawable.elwaicenterfmlogo
            134 -> R.drawable.countrypridefmlogo
            136 -> R.drawable.smoothjazz560logo
            137 -> R.drawable.lightfmlogo
            138 -> R.drawable.icedfmlogo
            139 -> R.drawable.geeradiologo
            140 -> R.drawable.tulwoobkoonyradiologo
            141 -> R.drawable.hootersfmlogo
            142 -> R.drawable.kufurahiafmlogo
            143 -> R.drawable.hoodradiologo
            144 -> R.drawable.abundanceradio
            145 -> R.drawable.aipcalogo
            146 -> R.drawable.msenangufmlogo
            149 -> R.drawable.tusmofmlogo
            150 -> R.drawable.radioshahidilogo
            151 -> R.drawable.pemiradiologo
            153 -> R.drawable.hypemagnetradiologo
            155 -> R.drawable.preachgospelradiologo
            156 -> R.drawable.radiomikayilogo
            157 -> R.drawable.konyonfmlogo
            158 -> R.drawable.pgradiologo
            161 -> R.drawable.doctorsexplainlogo
            162 -> R.drawable.edenmediaradiologo
            164 -> R.drawable.rasstyleradiologo
            165 -> R.drawable.optimumradiologo
            166 -> R.drawable.radiobarazalogo
            169 -> R.drawable.daradiologo
            170 -> R.drawable.uncutradiologo
            171 -> R.drawable.gracefmlogo
            202 -> R.drawable.radiochichilogo
            221 -> R.drawable.theophilusfmlogo
            222 -> R.drawable.ebruradiologo
            172 -> R.drawable.vybesradiologo
            173 -> R.drawable.starfmlogo
            174 -> R.drawable.mwangazawanenofmlogo
            175 -> R.drawable.thequestradiologo
            176 -> R.drawable.radioasuronlogo
            177 -> R.drawable.ruimbofmlogo
            178 -> R.drawable.safinaradiologo
            179 -> R.drawable.sayarefmlogo
            180 -> R.drawable.prasieradiologo
            181 -> R.drawable.tognofm
            182 -> R.drawable.moronigospellogo
            183 -> R.drawable.mwanaspotifmlogo
            184 -> R.drawable.touchradiologo
            185 -> R.drawable.uigithaniofmlogo
            186 -> R.drawable.radioamanilogo
            187 -> R.drawable.ksmradiologo
            188 -> R.drawable.dapstreamradiologo
            189 -> R.drawable.engelosradiologo
            190 -> R.drawable.semafmlogo
            191 -> R.drawable.kochfmlogo
            194 -> R.drawable.serianfmlogo
            195 -> R.drawable.radiomlimalogo
            196 -> R.drawable.ggvfmlogo
            197 -> R.drawable.popoteradiologo
            198 -> R.drawable.radiotumainilogo
            199 -> R.drawable.badidearadiologo
            200 -> R.drawable.diplomatradiologo
            201 -> R.drawable.habeshingamusiclogo
            else -> R.drawable.ic_radio_default
        }
    }
}
