name: Android CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 17
      ANDROID_SDK_ROOT: ~/Android/Sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}
          key: android-sdk-${{ runner.os }}-latest
          restore-keys: |
            android-sdk-${{ runner.os }}-

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintRelease

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
        continue-on-error: true

      - name: Upload Unit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest

      - name: Run Instrumentation Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_3a
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload Instrumentation Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-report
          path: app/build/reports/androidTests/connected

      - name: Build AAB
        run: ./gradlew bundleRelease

      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab
